//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morphic.Client.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morphic.Client.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton_Text {
            get {
                return ResourceManager.GetString("ApplyButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying settings on your computer....
        /// </summary>
        public static string ApplyingSettingsOnYourComputerLabel_Content {
            get {
                return ResourceManager.GetString("ApplyingSettingsOnYourComputerLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking the.
        /// </summary>
        public static string ApplySettingsFromCloudVaultInstructions_Part1_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultInstructions_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button will cause the assistive technology and system setting in your Morphic Cloud Vault to be applied to this computer..
        /// </summary>
        public static string ApplySettingsFromCloudVaultInstructions_Part3_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultInstructions_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The current settings on this computer will be backed up on this computer -- so you can revert back to the current settings later..
        /// </summary>
        public static string ApplySettingsFromCloudVaultNote_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultNote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply my settings from my Cloud Vault.
        /// </summary>
        public static string ApplySettingsFromCloudVaultTitle_Content {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Date.
        /// </summary>
        public static string BackupDate_Text {
            get {
                return ResourceManager.GetString("BackupDate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change this preference later, by using the Morphic Menu..
        /// </summary>
        public static string ChangePreferenceLaterUsingMorphicMenu_Text {
            get {
                return ResourceManager.GetString("ChangePreferenceLaterUsingMorphicMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string CheckForUpdateHyperlink_Text {
            get {
                return ResourceManager.GetString("CheckForUpdateHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking.
        /// </summary>
        public static string ClickingBelowWillRestoreSettings_Part1_Text {
            get {
                return ResourceManager.GetString("ClickingBelowWillRestoreSettings_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from backup.
        /// </summary>
        public static string ClickingBelowWillRestoreSettings_Part2_Text {
            get {
                return ResourceManager.GetString("ClickingBelowWillRestoreSettings_Part2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to below will restore those settings to this computer..
        /// </summary>
        public static string ClickingBelowWillRestoreSettings_Part3_Text {
            get {
                return ResourceManager.GetString("ClickingBelowWillRestoreSettings_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking save will save them to your secure Cloud Vault..
        /// </summary>
        public static string ClickingSaveWillSaveSettingsToVault_Text {
            get {
                return ResourceManager.GetString("ClickingSaveWillSaveSettingsToVault_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseButton_Text {
            get {
                return ResourceManager.GetString("CloseButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting settings from your computer....
        /// </summary>
        public static string CollectingSettingsFromComputerLabel_Content {
            get {
                return ResourceManager.GetString("CollectingSettingsFromComputerLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm saving to your Morphic Cloud Vault.
        /// </summary>
        public static string ConfirmSavingToCloudVaultLabel_Content {
            get {
                return ResourceManager.GetString("ConfirmSavingToCloudVaultLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature allows you to move your accessibility and usability settings between computers - including the settings of your assistive technologies..
        /// </summary>
        public static string CopySettingsBetweenComputersDescription_Text {
            get {
                return ResourceManager.GetString("CopySettingsBetweenComputersDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Settings Between Computers.
        /// </summary>
        public static string CopySettingsBetweenComputersHeader_Text {
            get {
                return ResourceManager.GetString("CopySettingsBetweenComputersHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the settings in my Cloud Vault to set up this computer..
        /// </summary>
        public static string CopySettingsFromCloudVaultHyperlink_Text {
            get {
                return ResourceManager.GetString("CopySettingsFromCloudVaultHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy settings on this computer to my Cloud Vault.
        /// </summary>
        public static string CopySettingsToCloudVaultHyperlink_Text {
            get {
                return ResourceManager.GetString("CopySettingsToCloudVaultHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneButton_Text {
            get {
                return ResourceManager.GetString("DoneButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton_AutomationHelpText {
            get {
                return ResourceManager.GetString("LoginButton_AutomationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now use Morphic to apply these settings to another computer that has Morphic installed..
        /// </summary>
        public static string MorphicCanNowApplySavedSettingsToAnotherComputer_Text {
            get {
                return ResourceManager.GetString("MorphicCanNowApplySavedSettingsToAnotherComputer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton_Text {
            get {
                return ResourceManager.GetString("OkButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before they were applied, the old settings were backed up on this computer. To revert back to those settings use the.
        /// </summary>
        public static string OldSettingsWereBackedUp_Part1_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Restore settings from backup&quot;.
        /// </summary>
        public static string OldSettingsWereBackedUp_Part2_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command in the Morphic menu..
        /// </summary>
        public static string OldSettingsWereBackedUp_Part3_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you sit down at another computer with Morphic installed, remember to login with the email address you provided.
        /// </summary>
        public static string RememberYourLoginEmailAddress_Text {
            get {
                return ResourceManager.GetString("RememberYourLoginEmailAddress_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore from backup.
        /// </summary>
        public static string RestoreFromBackupButton_Text {
            get {
                return ResourceManager.GetString("RestoreFromBackupButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore settings from backup.
        /// </summary>
        public static string RestoreSettingsFromBackupHeader_Text {
            get {
                return ResourceManager.GetString("RestoreSettingsFromBackupHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last time Morphic applied a user’s settings to this user account on this computer, Morphic captured the settings already on the computer and saved them to a backup..
        /// </summary>
        public static string RestoreSettingsFromBackupHeaderDescription_Text {
            get {
                return ResourceManager.GetString("RestoreSettingsFromBackupHeaderDescription_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore settings from backup.
        /// </summary>
        public static string RestoreSettingsFromBackupWindow_Title {
            get {
                return ResourceManager.GetString("RestoreSettingsFromBackupWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton_Text {
            get {
                return ResourceManager.GetString("SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you can securely take them anywhere.
        /// </summary>
        public static string SecurelyTakeSettingsAnywhere_Text {
            get {
                return ResourceManager.GetString("SecurelyTakeSettingsAnywhere_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the community whose bar you would like to see now:.
        /// </summary>
        public static string SelectCurrentGroupHeader_Text {
            get {
                return ResourceManager.GetString("SelectCurrentGroupHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have collected the settings of your assistive technologies and of the accessibility and usability settings of your computer..
        /// </summary>
        public static string SettingsCollectionComplete_Text {
            get {
                return ResourceManager.GetString("SettingsCollectionComplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings on from your cloud vault have been applied to this Computer..
        /// </summary>
        public static string SettingsFromCloudVaultHaveBeenApplied_Text {
            get {
                return ResourceManager.GetString("SettingsFromCloudVaultHaveBeenApplied_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete!.
        /// </summary>
        public static string SettingsSaveCompleteLabel_Content {
            get {
                return ResourceManager.GetString("SettingsSaveCompleteLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved to Cloud Vault.
        /// </summary>
        public static string SettingsSavedToCloudVaultLabel_Content {
            get {
                return ResourceManager.GetString("SettingsSavedToCloudVaultLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Morphic.
        /// </summary>
        public static string SignInWindow_Title {
            get {
                return ResourceManager.GetString("SignInWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel with Settings.
        /// </summary>
        public static string TravelWindow_Title {
            get {
                return ResourceManager.GetString("TravelWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morphic.
        /// </summary>
        public static string UntitledWindow_Title {
            get {
                return ResourceManager.GetString("UntitledWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve saved your settings in a secure area only you can access..
        /// </summary>
        public static string WeSavedYourSettings_Text {
            get {
                return ResourceManager.GetString("WeSavedYourSettings_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a member of several Morphic Groups..
        /// </summary>
        public static string YouAreMemberOfMultipleGroups_Text {
            get {
                return ResourceManager.GetString("YouAreMemberOfMultipleGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Settings have been applied.
        /// </summary>
        public static string YourSettingsHaveBeenAppliedLabel_Content {
            get {
                return ResourceManager.GetString("YourSettingsHaveBeenAppliedLabel_Content", resourceCulture);
            }
        }
    }
}
