//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morphic.Client.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morphic.Client.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Morphic.
        /// </summary>
        public static string AboutMorphicWindow_Title {
            get {
                return ResourceManager.GetString("AboutMorphicWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ApplyButton_Text {
            get {
                return ResourceManager.GetString("ApplyButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying settings on your computer....
        /// </summary>
        public static string ApplyingSettingsOnYourComputerLabel_Content {
            get {
                return ResourceManager.GetString("ApplyingSettingsOnYourComputerLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking the.
        /// </summary>
        public static string ApplySettingsFromCloudVaultInstructions_Part1_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultInstructions_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button will cause the assistive technology and system setting in your Morphic Cloud Vault to be applied to this computer..
        /// </summary>
        public static string ApplySettingsFromCloudVaultInstructions_Part3_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultInstructions_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The current settings on this computer will be backed up on this computer -- so you can revert back to the current settings later..
        /// </summary>
        public static string ApplySettingsFromCloudVaultNote_Text {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultNote_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply my settings from my Cloud Vault.
        /// </summary>
        public static string ApplySettingsFromCloudVaultTitle_Content {
            get {
                return ResourceManager.GetString("ApplySettingsFromCloudVaultTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Login.
        /// </summary>
        public static string CancelButton_AutomationHelpText {
            get {
                return ResourceManager.GetString("CancelButton_AutomationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton_Text {
            get {
                return ResourceManager.GetString("CancelButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change this preference later, by using the Morphic Menu..
        /// </summary>
        public static string ChangePreferenceLaterUsingMorphicMenu_Text {
            get {
                return ResourceManager.GetString("ChangePreferenceLaterUsingMorphicMenu_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Update.
        /// </summary>
        public static string CheckForUpdateHyperlink_Text {
            get {
                return ResourceManager.GetString("CheckForUpdateHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking save will save them to your secure Cloud Vault..
        /// </summary>
        public static string ClickingSaveWillSaveSettingsToVault_Text {
            get {
                return ResourceManager.GetString("ClickingSaveWillSaveSettingsToVault_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting settings from your computer....
        /// </summary>
        public static string CollectingSettingsFromComputerLabel_Content {
            get {
                return ResourceManager.GetString("CollectingSettingsFromComputerLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm saving to your Morphic Cloud Vault.
        /// </summary>
        public static string ConfirmSavingToCloudVaultLabel_Content {
            get {
                return ResourceManager.GetString("ConfirmSavingToCloudVaultLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account yet?.
        /// </summary>
        public static string CreateAccountHyperlink_Text {
            get {
                return ResourceManager.GetString("CreateAccountHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailFieldLabel_Text {
            get {
                return ResourceManager.GetString("EmailFieldLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password - Or not sure if you have an account?.
        /// </summary>
        public static string ForgotPasswordHyperlink_Text {
            get {
                return ResourceManager.GetString("ForgotPasswordHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More About Morphic.
        /// </summary>
        public static string LearnMoreAboutMorphicHyperlink_Text {
            get {
                return ResourceManager.GetString("LearnMoreAboutMorphicHyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginButton_AutomationHelpText {
            get {
                return ResourceManager.GetString("LoginButton_AutomationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We did not recognize your login.  Please try again..
        /// </summary>
        public static string LoginError_DidNotRecognizeLogin_Text {
            get {
                return ResourceManager.GetString("LoginError_DidNotRecognizeLogin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About Morphic....
        /// </summary>
        public static string Menu_AboutMorphic_Header {
            get {
                return ResourceManager.GetString("Menu_AboutMorphic_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a Saved Setup....
        /// </summary>
        public static string Menu_ApplySavedSetup_Header {
            get {
                return ResourceManager.GetString("Menu_ApplySavedSetup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Automatically start Morphic.
        /// </summary>
        public static string Menu_AutorunAfterLoginItem_Checkbox_Header {
            get {
                return ResourceManager.GetString("Menu_AutorunAfterLoginItem_Checkbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change MorphicBar.
        /// </summary>
        public static string Menu_ChangeMorphicBar_Header {
            get {
                return ResourceManager.GetString("Menu_ChangeMorphicBar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize MorphicBar....
        /// </summary>
        public static string Menu_CustomizeMorphicBar_Header {
            get {
                return ResourceManager.GetString("Menu_CustomizeMorphicBar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Explore everything Morphic can do....
        /// </summary>
        public static string Menu_ExploreMorphicLink_Header {
            get {
                return ResourceManager.GetString("Menu_ExploreMorphicLink_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide MorphicBar.
        /// </summary>
        public static string Menu_HideMorphicBar_Header {
            get {
                return ResourceManager.GetString("Menu_HideMorphicBar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Hide QuickHelp (except with Alt key).
        /// </summary>
        public static string Menu_HideQuickHelp_Header {
            get {
                return ResourceManager.GetString("Menu_HideQuickHelp_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to copy setups between computers....
        /// </summary>
        public static string Menu_HowToCopySettingsBetweenComputers_Header {
            get {
                return ResourceManager.GetString("Menu_HowToCopySettingsBetweenComputers_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More settings to make the computer easier.
        /// </summary>
        public static string Menu_MoreSettingsToMakeComputerEasier_Header {
            get {
                return ResourceManager.GetString("Menu_MoreSettingsToMakeComputerEasier_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All Accessibility Options.
        /// </summary>
        public static string Menu_OsAllAccessibilityOptions_Header {
            get {
                return ResourceManager.GetString("Menu_OsAllAccessibilityOptions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string Menu_OsBrightnessSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsBrightnessSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Color Vision Settings.
        /// </summary>
        public static string Menu_OsColorVisionSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsColorVisionSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Contrast Settings.
        /// </summary>
        public static string Menu_OsContrastSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsContrastSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Dark Mode Settings.
        /// </summary>
        public static string Menu_OsDarkModeSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsDarkModeSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct actions.
        /// </summary>
        public static string Menu_OsDirectionActionsSection_Header {
            get {
                return ResourceManager.GetString("Menu_OsDirectionActionsSection_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Keyboard Settings.
        /// </summary>
        public static string Menu_OsKeyboardSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsKeyboardSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Language.
        /// </summary>
        public static string Menu_OsLanguageSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsLanguageSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Magnifier Settings.
        /// </summary>
        public static string Menu_OsMagnifierSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsMagnifierSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M_ouse Settings.
        /// </summary>
        public static string Menu_OsMouseSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsMouseSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Night Mode Settings.
        /// </summary>
        public static string Menu_OsNightModeSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsNightModeSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Key Windows Settings.
        /// </summary>
        public static string Menu_OsOtherSettingsSection_Header {
            get {
                return ResourceManager.GetString("Menu_OsOtherSettingsSection_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pointer Size.
        /// </summary>
        public static string Menu_OsPointerSizeSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsPointerSizeSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Read Aloud Settings.
        /// </summary>
        public static string Menu_OsReadAloudSettings_Header {
            get {
                return ResourceManager.GetString("Menu_OsReadAloudSettings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Settings for MorphicBar Controls.
        /// </summary>
        public static string Menu_OsSettingsSection_Header {
            get {
                return ResourceManager.GetString("Menu_OsSettingsSection_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop Key-repeat.
        /// </summary>
        public static string Menu_OsStopKeyRepeatAction_Header {
            get {
                return ResourceManager.GetString("Menu_OsStopKeyRepeatAction_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Other resources to make computers easier....
        /// </summary>
        public static string Menu_OtherHelpfulThings_Header {
            get {
                return ResourceManager.GetString("Menu_OtherHelpfulThings_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problems? Contact us....
        /// </summary>
        public static string Menu_ProblemsContactUs_Header {
            get {
                return ResourceManager.GetString("Menu_ProblemsContactUs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Morphic _demo videos....
        /// </summary>
        public static string Menu_QuickMorphicDemosLink_Header {
            get {
                return ResourceManager.GetString("Menu_QuickMorphicDemosLink_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Quit Morphic.
        /// </summary>
        public static string Menu_QuitMorphic_Header {
            get {
                return ResourceManager.GetString("Menu_QuitMorphic_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Restore settings from backup.
        /// </summary>
        public static string Menu_RestoreSettingsFromBackup_Header {
            get {
                return ResourceManager.GetString("Menu_RestoreSettingsFromBackup_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Current Setup as....
        /// </summary>
        public static string Menu_SaveCurrentSetupAs_Header {
            get {
                return ResourceManager.GetString("Menu_SaveCurrentSetupAs_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic MorphicBar.
        /// </summary>
        public static string Menu_SelectBasicMorphicBar_Header {
            get {
                return ResourceManager.GetString("Menu_SelectBasicMorphicBar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show MorphicBar.
        /// </summary>
        public static string Menu_ShowMorphicBar_Header {
            get {
                return ResourceManager.GetString("Menu_ShowMorphicBar_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show Morphic Bar at start.
        /// </summary>
        public static string Menu_ShowMorphicBarLoginItem_Checkbox_Header {
            get {
                return ResourceManager.GetString("Menu_ShowMorphicBarLoginItem_Checkbox_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into Morphic....
        /// </summary>
        public static string Menu_SignIn_Header {
            get {
                return ResourceManager.GetString("Menu_SignIn_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out of Morphic.
        /// </summary>
        public static string Menu_SignOut_Header {
            get {
                return ResourceManager.GetString("Menu_SignOut_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can now use Morphic to apply these settings to another computer that has Morphic installed..
        /// </summary>
        public static string MorphicCanNowApplySavedSettingsToAnotherComputer_Text {
            get {
                return ResourceManager.GetString("MorphicCanNowApplySavedSettingsToAnotherComputer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButton_Text {
            get {
                return ResourceManager.GetString("OkButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before they were applied, the old settings were backed up on this computer. To revert back to those settings use the.
        /// </summary>
        public static string OldSettingsWereBackedUp_Part1_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Restore settings from backup&quot;.
        /// </summary>
        public static string OldSettingsWereBackedUp_Part2_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to command in the Morphic menu..
        /// </summary>
        public static string OldSettingsWereBackedUp_Part3_Text {
            get {
                return ResourceManager.GetString("OldSettingsWereBackedUp_Part3_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Morphic password.
        /// </summary>
        public static string PasswordField_AutomationHelpText {
            get {
                return ResourceManager.GetString("PasswordField_AutomationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordFieldLabel_Text {
            get {
                return ResourceManager.GetString("PasswordFieldLabel_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton_Text {
            get {
                return ResourceManager.GetString("SaveButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you can securely take them anywhere.
        /// </summary>
        public static string SecurelyTakeSettingsAnywhere_Text {
            get {
                return ResourceManager.GetString("SecurelyTakeSettingsAnywhere_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the community whose bar you would like to see now:.
        /// </summary>
        public static string SelectCurrentGroupHeader_Text {
            get {
                return ResourceManager.GetString("SelectCurrentGroupHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have collected the settings of your assistive technologies and of the accessibility and usability settings of your computer..
        /// </summary>
        public static string SettingsCollectionComplete_Text {
            get {
                return ResourceManager.GetString("SettingsCollectionComplete_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings on from your cloud vault have been applied to this Computer..
        /// </summary>
        public static string SettingsFromCloudVaultHaveBeenApplied_Text {
            get {
                return ResourceManager.GetString("SettingsFromCloudVaultHaveBeenApplied_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Saved to Cloud Vault.
        /// </summary>
        public static string SettingsSavedToCloudVaultLabel_Content {
            get {
                return ResourceManager.GetString("SettingsSavedToCloudVaultLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string SignInButton_Text {
            get {
                return ResourceManager.GetString("SignInButton_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign into your Morphic Account - Cloud Vault.
        /// </summary>
        public static string SignIntoMorphicAccountHeader_Text {
            get {
                return ResourceManager.GetString("SignIntoMorphicAccountHeader_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to Morphic.
        /// </summary>
        public static string SignInWindow_Title {
            get {
                return ResourceManager.GetString("SignInWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel with Settings.
        /// </summary>
        public static string TravelWindow_Title {
            get {
                return ResourceManager.GetString("TravelWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string UsernameField_AutomationHelpText {
            get {
                return ResourceManager.GetString("UsernameField_AutomationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are a member of several Morphic Groups..
        /// </summary>
        public static string YouAreMemberOfMultipleGroups_Text {
            get {
                return ResourceManager.GetString("YouAreMemberOfMultipleGroups_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Settings have been applied.
        /// </summary>
        public static string YourSettingsHaveBeenAppliedLabel_Content {
            get {
                return ResourceManager.GetString("YourSettingsHaveBeenAppliedLabel_Content", resourceCulture);
            }
        }
    }
}
