// Copyright 2020-2026 Raising the Floor - US, Inc.
//
// Licensed under the New BSD license. You may not use this file except in
// compliance with this License.
//
// You may obtain a copy of the License at
// https://github.com/raisingthefloor/morphic-windowsnative-lib-cs/blob/main/LICENSE
//
// The R&D leading to these results received funding from the:
// * Rehabilitation Services Administration, US Dept. of Education under
//   grant H421A150006 (APCP)
// * National Institute on Disability, Independent Living, and
//   Rehabilitation Research (NIDILRR)
// * Administration for Independent Living & Dept. of Education under grants
//   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
// * European Union's Seventh Framework Programme (FP7/2007-2013) grant
//   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
// * William and Flora Hewlett Foundation
// * Ontario Ministry of Research and Innovation
// * Canadian Foundation for Innovation
// * Adobe Foundation
// * Consumer Electronics Association Foundation

using Morphic.Core;
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using SystemSettings_DataModel = SystemSettings.DataModel; // generated by CsWinRT

namespace Morphic.WindowsNative.SystemSettings;

internal class SettingItemProxy
{
    // NOTE: this enum should match SystemSettings.DataModel.SettingType; it may seem redundant, but we are providing it so that we can use the raw SystemSettings classes internally
    //       (WinRT interop) and expose a stable value externally
    public enum SettingType
    {
        Action,
        Boolean,
        Custom,
        DisplayString,
        LabeledString,
        List,
        Plugin,
        Range,
        SettingCollection,
        String
    }

    private SystemSettings_DataModel.ISettingItem _settingItem;

    internal SettingItemProxy(SystemSettings_DataModel.ISettingItem settingItem)
    {
        _settingItem = settingItem;
    }
    public string Id => _settingItem.Id;
    public bool IsApplicable => _settingItem.IsApplicable;
    public bool IsEnabled => _settingItem.IsEnabled;

    //

    #region Get SettingType

    public interface IGetSettingTypeError
    {
        public record ExceptionError(Exception Ex) : IGetSettingTypeError;
        public record UnknownType : IGetSettingTypeError;
    }
    //
    public MorphicResult<SettingItemProxy.SettingType, IGetSettingTypeError> GetSettingType()
    {
        // NOTE: we're unsure if ISettingItem.GetType() can throw an exception; we're catching exceptions anyway, out of an abundance of caution
        SystemSettings_DataModel.SettingType settingItemType;
        try
        {
            settingItemType = _settingItem.Type;
        }
        catch (Exception ex)
        {
            return MorphicResult.ErrorResult<IGetSettingTypeError>(new IGetSettingTypeError.ExceptionError(ex));
        }

        // convert the setting item's type to the publicly-exposed SettingItemProxy.SettingType enum
        SettingItemProxy.SettingType? result = SettingItemProxy.ConvertWinRtSettingTypeToPublicSettingType(settingItemType);
        if (result is null)
        {
            return MorphicResult.ErrorResult<IGetSettingTypeError>(new IGetSettingTypeError.UnknownType());
        }
        else
        {
            return MorphicResult.OkResult(result!.Value);
        }
    }

    private static SettingItemProxy.SettingType? ConvertWinRtSettingTypeToPublicSettingType(SystemSettings_DataModel.SettingType settingType)
    {
        switch (settingType)
        {
            case SystemSettings_DataModel.SettingType.Action:
                return SettingItemProxy.SettingType.Action;
            case SystemSettings_DataModel.SettingType.Boolean:
                return SettingItemProxy.SettingType.Boolean;
            case SystemSettings_DataModel.SettingType.Custom:
                return SettingItemProxy.SettingType.Custom;
            case SystemSettings_DataModel.SettingType.DisplayString:
                return SettingItemProxy.SettingType.DisplayString;
            case SystemSettings_DataModel.SettingType.LabeledString:
                return SettingItemProxy.SettingType.LabeledString;
            case SystemSettings_DataModel.SettingType.List:
                return SettingItemProxy.SettingType.List;
            case SystemSettings_DataModel.SettingType.Plugin:
                return SettingItemProxy.SettingType.Plugin;
            case SystemSettings_DataModel.SettingType.Range:
                return SettingItemProxy.SettingType.Range;
            case SystemSettings_DataModel.SettingType.SettingCollection:
                return SettingItemProxy.SettingType.SettingCollection;
            case SystemSettings_DataModel.SettingType.String:
                return SettingItemProxy.SettingType.String;
            default:
                return null;
        }
    }

    #endregion Get SettingType

    //

    #region Set Value

    public interface ISetValueError
    {
        public record ExceptionError(Exception Ex) : ISetValueError;
        //public record SettingNotApplicableOrNotEnabledAfterSet : ISetValueError;
        public record Timeout : ISetValueError;
        //public record TypeMismatch : ISetValueError;
    }

    // NOTE: both the struct- and class-specific implementations of SetValueAsync MUST be kept in sync!
    //
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(T value, TimeSpan? timeout = null) where T : struct
    {
        var result = await this.SetValueAsync("Value", value, timeout);
        return result;
    }
    //
    // NOTE: callers should "get" the value after setting it, just to be sure that the value was set correctly.  [Note that technically another app could be setting the value
    //       in parallel, so if the value doesn't match then we can't really be sure that our "set" wasn't reversed by another app.]
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(string name, T value, TimeSpan? timeout = null) where T : struct
    {
        return await this.SetValueAsObjectAsync(name, value, timeout);
    }

    // NOTE: both the struct- and class-specific implementations of SetValueAsync MUST be kept in sync!
    //
    // NOTE: this second implementation of SetValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(T value, TimeSpan? timeout = null, object? _ = null) where T : class
    {
        var result = await this.SetValueAsync("Value", value, timeout);
        return result;
    }
    //
    // NOTE: callers should "get" the value after setting it, just to be sure that the value was set correctly.  [Note that technically another app could be setting the value
    //       in parallel, so if the value doesn't match then we can't really be sure that our "set" wasn't reversed by another app.]
    // NOTE: this second implementation of SetValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(string name, T value, TimeSpan? timeout = null, object? _ = null) where T : class
    {
        return await this.SetValueAsObjectAsync(name, value, timeout);
    }

    // NOTE: if the setting is disabled while it is being set, this function's 'set' operation could fail even though it returns success
    private async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsObjectAsync(string name, object value, TimeSpan? timeout = null)
    {
        if (timeout is null)
        {
            timeout = TimeSpan.Zero;
        }
        if (timeout!.Value.TotalMilliseconds > int.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(timeout), "Timeout may not exceed Int32.MaxValue milliseconds.");
        }
        var timeoutInMilliseconds = (int)timeout!.Value.TotalMilliseconds;

        Stopwatch timeoutStopwatch = Stopwatch.StartNew();

        // step 1: make sure that the setting is both applicable and enabled
        // NOTE: in our analysis of ISettingItem, IsApplicable was usually set to true whenever IsEnabled was--but with some settings (like the apps/system dark theme settings),
        //       IsApplicable was always false; if we feel like we need to be extra-cautious (i.e. we think that IsApplicable is a critical thing to check), we can pass an extra
        //       argument into "WaitForIsEnabledEventAsync" to also watch for IsApplicable to be true
        var remainingTimeout = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
        var waitResult = await this.WaitForIsEnabledEventAsync(remainingTimeout);
        if (waitResult.IsError == true)
        {
            switch (waitResult.Error!)
            {
                case IMorphicTimeoutError.Timeout:
                    return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.Timeout());
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }

        // STEP 2: once the value state is (hopefully) valid, set the value of the setting
        // NOTE: theoretically, IsEnabled could be set to false at any moment so we are not 100% guaranteed that our "set" will actually set the value; the caller may want to
        //       capture the "ValueChanged" and/or "IsApplicable/IsEnabled" event handlers to react to the actual value change, to ensure that the value changed, etc.
        // NOTE: we're unsure if ISettingItem.SetValue(string, object) can throw an exception; we're catching exceptions anyway, out of an abundance of caution
        try
        {
            _settingItem.SetValue(name, value);
        }
        catch (Exception ex)
        {
            // NOTE: if the exception returned here is "type mismatch", we should return that as an error instead
            return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.ExceptionError(ex));
        }

        // NOTE: as we aren't confident that IsApplicable/IsEnabled won't be changed as a result of our SET operation, we have commented out this step (but can bring it back,
        //       if further analysis shows that it is necessary or useful)
        //// STEP 3: make sure that the setting is still applicable/enabled (see notes on STEP 1), as a sanity check that our value was set correctly
        //bool isApplicable = _settingItem.IsApplicable;
        //bool isEnabled = _settingItem.IsEnabled;
        //if (isApplicable == true && isEnabled == true)
        //{
        //    // continue; all is good
        //}
        //else
        //{
        //    return MorphicResult.ErrorResult(SetValueError.SettingNotApplicableOrNotEnabledAfterSet);
        //}

        // STEP 4: return success
        return MorphicResult.OkResult();
    }

    //

    private async Task<MorphicResult<MorphicUnit, IMorphicTimeoutError>> WaitForIsEnabledEventAsync(int timeoutInMilliseconds, bool alsoWaitForApplicable = false)
    {
        var propertyChangedWaitHandle = new AutoResetEvent(false);
        var propertyChangedHandler = new Windows.Foundation.TypedEventHandler<object, string>((object sender, string args) =>
        {
            switch (args)
            {
                case "IsApplicable":
                    if (alsoWaitForApplicable == true)
                    {
                        propertyChangedWaitHandle.Set();
                    }
                    break;
                case "IsEnabled":
                    propertyChangedWaitHandle.Set();
                    break;
                default:
                    break;
            }
        });
        var isWatchingForPropertyChangedEvent = false;

        var isConditionSatisfied = () => {
            var isApplicable = _settingItem.IsApplicable;
            var isEnabled = _settingItem.IsEnabled;

            var conditionSatisfied = false;
            //
            // check our base condition
            if (isEnabled == true)
            {
                conditionSatisfied = true;
            }
            //
            // check our additional (optional) conditions
            if (alsoWaitForApplicable == true)
            {
                if (isApplicable == false)
                {
                    conditionSatisfied = false;
                }
            }

            return conditionSatisfied;
        };

        try
        {
            Stopwatch timeoutStopwatch = Stopwatch.StartNew();
            // NOTE: we use an infinite loop so that we can wait multiple times (if, for instance, we get events for only one of multiple states); it will terminate upon timeout in the 
            //       worst-case scenario
            while (true)
            {
                // for every iteration of the loop, we check to see if the condition is satisfied
                if (isConditionSatisfied() == true)
                {
                    break;
                }

                // if we're not already watching for the propert(ies) to change, wire up an event handler now
                if (isWatchingForPropertyChangedEvent == false)
                {
                    _settingItem.SettingChanged += propertyChangedHandler;
                    isWatchingForPropertyChangedEvent = true;

                    // check to see if the condition is satisfied one more time, just in case the condition became satisfied at the same time we were setting up the event
                    if (isConditionSatisfied() == true)
                    {
                        break;
                    }
                }

                // NOTE: if we reach this point, we are not ready yet; we need to wait for the corresponding event(s) to change
                var remainingTimeout = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
                if (remainingTimeout == 0)
                {
                    return MorphicResult.ErrorResult<IMorphicTimeoutError>(new IMorphicTimeoutError.Timeout());
                }
                
                // wait for the IsApplicable/IsEnabled event handler to fire (or for our timeout to expire, whichever comes first)
                TaskCompletionSource<bool>? taskCompletionSource = new TaskCompletionSource<bool>();
                //
                // NOTE: we treat taskCompletionSource as nullable here just in case it the delegate gets called after the function completes (which should not happen, but we saw a null taskCompletionSource once in testing)
                var waitHandleRegistration = ThreadPool.RegisterWaitForSingleObject(propertyChangedWaitHandle, delegate { taskCompletionSource?.SetResult(true); }, null, remainingTimeout, true);
                try
                {
                    _ = await taskCompletionSource!.Task.WaitAsync(new TimeSpan(0, 0, 0, 0, remainingTimeout));
                }
                catch (TimeoutException)
                {
                    // swallow the TimeoutException; we'll capture this timeout in the next loop iteration
                    //return MorphicResult.ErrorResult(MorphicTimeoutError.Timeout);
                }
                finally
                {
                    // NOTE: we do not need to signal any wait handle when we unregister the wait handle registration (i.e. the waitObject param is null)
                    waitHandleRegistration.Unregister(null);
                }
            }

            return MorphicResult.OkResult();
        }
        finally
        {
            if (isWatchingForPropertyChangedEvent == true)
            {
                _settingItem.SettingChanged -= propertyChangedHandler;
                isWatchingForPropertyChangedEvent = false;
            }
        }
    }

    #endregion Set Value

    //

    #region Static helpers

    public interface ISetSettingItemValueError
    {
        public record ExceptionError(Exception Ex) : ISetSettingItemValueError;
        public record SettingItemIsNull : ISetSettingItemValueError;
        //public record SetSettingItemValueError SettingNotApplicableOrNotEnabledAfterSet : ISetSettingItemValueError;
        public record Timeout : ISetSettingItemValueError;
        //public record TypeMismatch : ISetSettingItemValueError;
    }

    // NOTE: both the struct- and class-specific implementations of SetSettingItemValueAsync MUST be kept in sync!
    //
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, T value, TimeSpan? timeout = null) where T : struct
    {
        return await SettingItemProxy.SetSettingItemValueAsync<T>(settingItem, "Value", value, timeout);
    }
    //
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, string name, T value, TimeSpan? timeout = null) where T : struct
    {
        return await SettingItemProxy.SetSettingItemValueAsObjectAsync(settingItem, name, value, timeout);
    }

    // NOTE: both the struct and class-specific implementations of SetSettingItemValueAsync MUST be kept in sync!
    //
    // NOTE: this second implementation of SetSettingItemValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, T value, TimeSpan? timeout = null, object? _ = null) where T : class
    {
        return await SettingItemProxy.SetSettingItemValueAsync<T>(settingItem, "Value", value, timeout);
    }
    //
    // NOTE: this second implementation of SetSettingItemValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, string name, T value, TimeSpan? timeout = null, object? _ = null) where T : class
    {
        return await SettingItemProxy.SetSettingItemValueAsObjectAsync(settingItem, name, value, timeout);
    }

    private async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsObjectAsync(SettingItemProxy? settingItem, string name, object value, TimeSpan? timeout = null)
    {
        // NOTE: for 'binding-style' convenience, we let the caller pass in a nullable SettingItem; they'll just get an error result in return, however
        if (settingItem is null)
        {
            return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.SettingItemIsNull());
        }

        MorphicResult<MorphicUnit, Morphic.WindowsNative.SystemSettings.SettingItemProxy.ISetValueError> setSettingResult;
        setSettingResult = await settingItem.SetValueAsObjectAsync(name, value, timeout);
        if (setSettingResult.IsError == true)
        {
            switch (setSettingResult.Error!)
            {
                case ISetValueError.ExceptionError(var ex):
                    {
                        return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.ExceptionError(ex));
                    }
                case ISetValueError.Timeout:
                    return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.Timeout());
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }

        return MorphicResult.OkResult();
    }

    #endregion Static helpers
}
