// Copyright 2020-2026 Raising the Floor - US, Inc.
//
// Licensed under the New BSD license. You may not use this file except in
// compliance with this License.
//
// You may obtain a copy of the License at
// https://github.com/raisingthefloor/morphic-windowsnative-lib-cs/blob/main/LICENSE
//
// The R&D leading to these results received funding from the:
// * Rehabilitation Services Administration, US Dept. of Education under
//   grant H421A150006 (APCP)
// * National Institute on Disability, Independent Living, and
//   Rehabilitation Research (NIDILRR)
// * Administration for Independent Living & Dept. of Education under grants
//   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
// * European Union's Seventh Framework Programme (FP7/2007-2013) grant
//   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
// * William and Flora Hewlett Foundation
// * Ontario Ministry of Research and Innovation
// * Canadian Foundation for Innovation
// * Adobe Foundation
// * Consumer Electronics Association Foundation

using Morphic.Core;
using System;
using System.Diagnostics;
using System.Threading;
using System.Threading.Tasks;
using SystemSettings_DataModel = SystemSettings.DataModel; // generated by CsWinRT

namespace Morphic.WindowsNative.SystemSettings;

internal class SettingItemProxy
{
    // Default timeout applied when callers pass `timeout = null` (which is the parameter's own
    // default). Five seconds covers the cold-start case where a SettingItem's IsEnabled flag is
    // still propagating from false to true at the moment of the first Get/Set call.
    //
    // Callers who want "fail-fast" behavior instead can pass TimeSpan.Zero explicitly.
    private static readonly TimeSpan DefaultTimeout = TimeSpan.FromSeconds(5);

    // NOTE: this enum should match SystemSettings.DataModel.SettingType; it may seem redundant, but we are providing it so that we can use the raw SystemSettings classes internally
    //       (WinRT interop) and expose a stable value externally
    public enum SettingType
    {
        Action,
        Boolean,
        Custom,
        DisplayString,
        LabeledString,
        List,
        Plugin,
        Range,
        SettingCollection,
        String
    }

    private readonly SystemSettings_DataModel.ISettingItem _settingItem;

    internal SettingItemProxy(SystemSettings_DataModel.ISettingItem settingItem)
    {
        _settingItem = settingItem;
    }
	
    // Read accessors for the WinRT-side properties. Returned as MorphicResults rather than bare
    // values so the COMException risk of touching the underlying WinRT proxy can be surfaced
    // through the same error channel the rest of the class uses, rather than escaping as an
    // uncaught exception.
    public MorphicResult<string, IMorphicExceptionError> GetId()
    {
        try
        {
            return MorphicResult.OkResult(SettingItemDispatcher.Run(() => _settingItem.Id));
        }
        catch (Exception ex)
        {
            return MorphicResult.ErrorResult<IMorphicExceptionError>(new IMorphicExceptionError.Exception(ex));
        }
    }

    public MorphicResult<bool, IMorphicExceptionError> GetIsApplicable()
    {
        try
        {
            return MorphicResult.OkResult(SettingItemDispatcher.Run(() => _settingItem.IsApplicable));
        }
        catch (Exception ex)
        {
            return MorphicResult.ErrorResult<IMorphicExceptionError>(new IMorphicExceptionError.Exception(ex));
        }
    }

    public MorphicResult<bool, IMorphicExceptionError> GetIsEnabled()
    {
        try
        {
            return MorphicResult.OkResult(SettingItemDispatcher.Run(() => _settingItem.IsEnabled));
        }
        catch (Exception ex)
        {
            return MorphicResult.ErrorResult<IMorphicExceptionError>(new IMorphicExceptionError.Exception(ex));
        }
    }

    //

    // variables for handling events
    private bool _settingsChangedEventHandlerIsSubscribed = false;
    //
    private EventHandler? _isApplicableChanged = null;
    private EventHandler? _isEnabledChanged = null;
    private EventHandler? _valueChanged = null;
    //
    private readonly object _eventsLock = new object();

    //

    #region Get SettingType

    public interface IGetSettingTypeError
    {
        public record ExceptionError(Exception Ex) : IGetSettingTypeError;
        public record UnknownType : IGetSettingTypeError;
    }
    //
    public MorphicResult<SettingItemProxy.SettingType, IGetSettingTypeError> GetSettingType()
    {
        // NOTE: we're unsure if ISettingItem.GetType() can throw an exception; we're catching exceptions anyway, out of an abundance of caution
        SystemSettings_DataModel.SettingType settingItemType;
        try
        {
            settingItemType = SettingItemDispatcher.Run(() => _settingItem.Type);
        }
        catch (Exception ex)
        {
            return MorphicResult.ErrorResult<IGetSettingTypeError>(new IGetSettingTypeError.ExceptionError(ex));
        }

        // convert the setting item's type to the publicly-exposed SettingItemProxy.SettingType enum
        SettingItemProxy.SettingType? result = SettingItemProxy.ConvertWinRtSettingTypeToPublicSettingType(settingItemType);
        if (result is null)
        {
            return MorphicResult.ErrorResult<IGetSettingTypeError>(new IGetSettingTypeError.UnknownType());
        }
        else
        {
            return MorphicResult.OkResult(result!.Value);
        }
    }

    private static SettingItemProxy.SettingType? ConvertWinRtSettingTypeToPublicSettingType(SystemSettings_DataModel.SettingType settingType)
    {
        switch (settingType)
        {
            case SystemSettings_DataModel.SettingType.Action:
                return SettingItemProxy.SettingType.Action;
            case SystemSettings_DataModel.SettingType.Boolean:
                return SettingItemProxy.SettingType.Boolean;
            case SystemSettings_DataModel.SettingType.Custom:
                return SettingItemProxy.SettingType.Custom;
            case SystemSettings_DataModel.SettingType.DisplayString:
                return SettingItemProxy.SettingType.DisplayString;
            case SystemSettings_DataModel.SettingType.LabeledString:
                return SettingItemProxy.SettingType.LabeledString;
            case SystemSettings_DataModel.SettingType.List:
                return SettingItemProxy.SettingType.List;
            case SystemSettings_DataModel.SettingType.Plugin:
                return SettingItemProxy.SettingType.Plugin;
            case SystemSettings_DataModel.SettingType.Range:
                return SettingItemProxy.SettingType.Range;
            case SystemSettings_DataModel.SettingType.SettingCollection:
                return SettingItemProxy.SettingType.SettingCollection;
            case SystemSettings_DataModel.SettingType.String:
                return SettingItemProxy.SettingType.String;
            default:
                return null;
        }
    }

    #endregion Get SettingType

    //

    #region Get Value

    public interface IGetValueError
    {
        public record ExceptionError(Exception Ex) : IGetValueError;
        public record Timeout : IGetValueError;
        public record TypeMismatch : IGetValueError;
    }
    //
    public async Task<MorphicResult<T?, IGetValueError>> GetValueAsync<T>(TimeSpan? timeout = null) where T : struct
    {
        var result = await this.GetValueAsync<T>("Value", timeout);
        return result;
    }
    //
    public async Task<MorphicResult<T?, IGetValueError>> GetValueAsync<T>(string name, TimeSpan? timeout = null) where T : struct
    {
        if (timeout is null)
        {
            timeout = SettingItemProxy.DefaultTimeout;
        }
        if (timeout!.Value.TotalMilliseconds > int.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(timeout), "Timeout may not exceed Int32.MaxValue milliseconds.");
        }
        var timeoutInMilliseconds = (int)timeout!.Value.TotalMilliseconds;

        Stopwatch timeoutStopwatch = Stopwatch.StartNew();

        object? valueAsObject;

        // NOTE: we check the value in an infinite loop in case the IsApplicable/IsEnabled settings are in flux; this allows us to handle edge case scenarios (which may never
        //       happen) where the setting is available and enabled, then we get the value, but then the setting is not available/enabled--so we're not totally confident in the
        //       value itself (i.e. we could be getting a null/false/default value instead); this is not a foolproof scenario, but it's our best attempt
        while (true)
        {
            // step 1: make sure that the setting is both applicable and enabled
            // NOTE: in our analysis of ISettingItem, IsApplicable was usually set to true whenever IsEnabled was--but with some settings (like the apps/system dark theme settings),
            //       IsApplicable was always false; if we feel like we need to be extra-cautious (i.e. we think that IsApplicable is a critical thing to check), we can pass an extra
            //       argument into "WaitForIsEnabledEventAsync" to also watch for IsApplicable to be true
            var remainingTimeout = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
            var waitResult = await this.WaitForIsEnabledEventAsync(remainingTimeout);
            if (waitResult.IsError == true)
            {
                switch (waitResult.Error!)
                {
                    case IWaitForSettingEventError.Timeout:
                        return MorphicResult.ErrorResult<IGetValueError>(new IGetValueError.Timeout());
                    case IWaitForSettingEventError.ExceptionError(var ex):
                        return MorphicResult.ErrorResult<IGetValueError>(new IGetValueError.ExceptionError(ex));
                    default:
                        throw new MorphicUnhandledErrorException();
                }
            }

            // STEP 2: once the value state is (hopefully) valid, capture the value of the setting
            // NOTE: theoretically, IsEnabled could be set to false at any moment so we are not 100% guaranteed to get the correct value; the caller should ideally use an event
            //       handler strategy to also capture updates to the value (since the "Value" SettingsChanged handler seems to be executed every time IsApplicable/IsEnabled or Value
            //       is updated...and they seem to be updated together, in that order)
            // NOTE: we're unsure if ISettingItem.GetValue(string) can throw an exception; we're catching exceptions anyway, out of an abundance of caution
            try
            {
                valueAsObject = SettingItemDispatcher.Run(() => _settingItem.GetValue(name));
                if (valueAsObject == null)
                {
                    return MorphicResult.OkResult<T?>(null);
                }
            }
            catch (Exception ex)
            {
                return MorphicResult.ErrorResult<IGetValueError>(new IGetValueError.ExceptionError(ex));
            }

            // STEP 3: make sure that the setting is still enabled (see notes on STEP 1), as a sanity check that our value is still good; note that this is not a failproof strategy.
            //
            // We deliberately do NOT also require IsApplicable here. Some real settings keep
            // IsApplicable==false permanently even when the value is fully readable (e.g. the
            // Win10 SystemUsesLightTheme / AppsUseLightTheme dark-theme toggles). Gating the
            // break on IsApplicable+IsEnabled spins the loop forever for those settings, since
            // WaitForIsEnabledEventAsync returns immediately when IsEnabled is already true and
            // each iteration succeeds at GetValue but then re-fails the sanity check.
            bool isEnabled;
            try
            {
                isEnabled = SettingItemDispatcher.Run(() => _settingItem.IsEnabled);
            }
            catch (Exception ex)
            {
                return MorphicResult.ErrorResult<IGetValueError>(new IGetValueError.ExceptionError(ex));
            }
            if (isEnabled == true)
            {
                break;
            }
            else
            {
                // continue to the next iteration of the loop; try, try again
            }
        }

        // STEP 4: if the value is deemed as almost-certainly valid, go ahead and attempt to cast it to type T now
        var valueAsT = valueAsObject as T?;
        if (valueAsT is null)
        {
            // the type provided by the caller is not cast-compatible with the type returned by WinRT
            return MorphicResult.ErrorResult<IGetValueError>(new IGetValueError.TypeMismatch());
        }

        // STEP 5: return the value to the caller
        return MorphicResult.OkResult<T?>(valueAsT!.Value);
    }

    #endregion Get Value

    //

    #region Set Value

    public interface ISetValueError
    {
        public record ExceptionError(Exception Ex) : ISetValueError;
        //public record SettingNotApplicableOrNotEnabledAfterSet : ISetValueError;
        public record Timeout : ISetValueError;
        //public record TypeMismatch : ISetValueError;
        public record ValueDidNotApplyAfterSet : ISetValueError;
    }

    // NOTE: both the struct- and class-specific implementations of SetValueAsync MUST be kept in sync!
    //
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(T value, TimeSpan? timeout = null, bool verifyAfterSet = true) where T : struct
    {
        var result = await this.SetValueAsync("Value", value, timeout, verifyAfterSet);
        return result;
    }
    //
    // NOTE: callers should "get" the value after setting it, just to be sure that the value was set correctly.  [Note that technically another app could be setting the value
    //       in parallel, so if the value doesn't match then we can't really be sure that our "set" wasn't reversed by another app.]
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(string name, T value, TimeSpan? timeout = null, bool verifyAfterSet = true) where T : struct
    {
        return await this.SetValueAsObjectAsync(name, value, timeout, verifyAfterSet);
    }

    // NOTE: both the struct- and class-specific implementations of SetValueAsync MUST be kept in sync!
    //
    // NOTE: this second implementation of SetValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(T value, TimeSpan? timeout = null, bool verifyAfterSet = true, object? _ = null) where T : class
    {
        var result = await this.SetValueAsync("Value", value, timeout, verifyAfterSet);
        return result;
    }
    //
    // NOTE: callers should "get" the value after setting it, just to be sure that the value was set correctly.  [Note that technically another app could be setting the value
    //       in parallel, so if the value doesn't match then we can't really be sure that our "set" wasn't reversed by another app.]
    // NOTE: this second implementation of SetValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsync<T>(string name, T value, TimeSpan? timeout = null, bool verifyAfterSet = true, object? _ = null) where T : class
    {
        return await this.SetValueAsObjectAsync(name, value, timeout, verifyAfterSet);
    }

    // NOTE: if the setting is disabled while it is being set, this function's 'set' operation could fail even though it returns success
    private async Task<MorphicResult<MorphicUnit, ISetValueError>> SetValueAsObjectAsync(string name, object value, TimeSpan? timeout = null, bool verifyAfterSet = true)
    {
        if (timeout is null)
        {
            timeout = SettingItemProxy.DefaultTimeout;
        }
        if (timeout!.Value.TotalMilliseconds > int.MaxValue)
        {
            throw new ArgumentOutOfRangeException(nameof(timeout), "Timeout may not exceed Int32.MaxValue milliseconds.");
        }
        var timeoutInMilliseconds = (int)timeout!.Value.TotalMilliseconds;

        Stopwatch timeoutStopwatch = Stopwatch.StartNew();

        // step 1: make sure that the setting is both applicable and enabled
        // NOTE: in our analysis of ISettingItem, IsApplicable was usually set to true whenever IsEnabled was--but with some settings (like the apps/system dark theme settings),
        //       IsApplicable was always false; if we feel like we need to be extra-cautious (i.e. we think that IsApplicable is a critical thing to check), we can pass an extra
        //       argument into "WaitForIsEnabledEventAsync" to also watch for IsApplicable to be true
        var remainingTimeoutBeforeSet = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
        var waitResult = await this.WaitForIsEnabledEventAsync(remainingTimeoutBeforeSet);
        if (waitResult.IsError == true)
        {
            switch (waitResult.Error!)
            {
                case IWaitForSettingEventError.Timeout:
                    return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.Timeout());
                case IWaitForSettingEventError.ExceptionError(var ex):
                    return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.ExceptionError(ex));
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }

        // STEP 2: once the value state is (hopefully) valid, set the value of the setting
        // NOTE: theoretically, IsEnabled could be set to false at any moment so we are not 100% guaranteed that our "set" will actually set the value; if the caller wants the
        //       "did the set actually take effect" question answered, they should leave verifyAfterSet at its default (true); STEP 3 below polls until the read-back value
        //       matches (within the remaining timeout) and returns ValueDidNotApplyAfterSet if it doesn't settle.
        // NOTE: we're unsure if ISettingItem.SetValue(string, object) can throw an exception; we're catching exceptions anyway, out of an abundance of caution
        try
        {
            // Wrapping each primitive via the corresponding PropertyValue.CreateXxx factory produces a
            // real WinRT IPropertyValue that the projection hands off to the native side without needing
            // further marshaling. Note: sbyte (Int8) has no PropertyValue factory because WinRT itself
            // doesn't define an Int8 primitive type; pass it as int (or accept whatever the projection
            // does) if a setting ever needs it.
            //
            // We do the wrap INSIDE the dispatcher delegate so the IPropertyValue itself is created on
            // the STA worker thread, keeping every WinRT object touched by SetValue in a single
            // apartment.
            SettingItemDispatcher.Run(() =>
            {
                object winrtValue = value switch
                {
                    bool b => Windows.Foundation.PropertyValue.CreateBoolean(b),
                    string s => Windows.Foundation.PropertyValue.CreateString(s),
                    byte u8 => Windows.Foundation.PropertyValue.CreateUInt8(u8),
                    short i16 => Windows.Foundation.PropertyValue.CreateInt16(i16),
                    ushort u16 => Windows.Foundation.PropertyValue.CreateUInt16(u16),
                    int i32 => Windows.Foundation.PropertyValue.CreateInt32(i32),
                    uint u32 => Windows.Foundation.PropertyValue.CreateUInt32(u32),
                    long i64 => Windows.Foundation.PropertyValue.CreateInt64(i64),
                    ulong u64 => Windows.Foundation.PropertyValue.CreateUInt64(u64),
                    float f => Windows.Foundation.PropertyValue.CreateSingle(f),
                    double d => Windows.Foundation.PropertyValue.CreateDouble(d),
                    char c => Windows.Foundation.PropertyValue.CreateChar16(c),
                    System.Guid g => Windows.Foundation.PropertyValue.CreateGuid(g),
                    System.DateTimeOffset dt => Windows.Foundation.PropertyValue.CreateDateTime(dt),
                    System.TimeSpan ts => Windows.Foundation.PropertyValue.CreateTimeSpan(ts),
                    _ => value,
                };

                _settingItem.SetValue(name, winrtValue);
            });
        }
        catch (Exception ex)
        {
            // NOTE: if the exception returned here is "type mismatch", we should return that as an error instead
            return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.ExceptionError(ex));
        }

        // STEP 3 (optional, default ON): verify that the value actually landed by reading it back
        // and comparing. Uses WaitForValueToEqualAsync, which subscribes to the SettingItem's
        // ValueChanged signal and re-reads on each change until either the read matches the value
        // we wrote, or the remaining timeout expires. This catches:
        //   * silent rejections (set returned without throwing, but the framework dropped the
        //     write -- e.g. due to policy or the setting going non-applicable mid-write),
        //   * propagation delays (some settings let SetValue return synchronously but actually
        //     propagate through an async chain; an immediate read-back would see the old value),
        //   * other clients writing different values in parallel.
        // Callers who want fire-and-forget semantics (and accept silent-fail risk) can pass
        // verifyAfterSet: false.
        if (verifyAfterSet == false)
        {
            return MorphicResult.OkResult();
        }
        //
        var remainingTimeoutForVerification = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
        var verifyResult = await this.WaitForValueToEqualAsync(name, value, remainingTimeoutForVerification);
        if (verifyResult.IsError == true)
        {
            switch (verifyResult.Error!)
            {
                case IWaitForSettingEventError.Timeout:
                    return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.ValueDidNotApplyAfterSet());
                case IWaitForSettingEventError.ExceptionError(var ex):
                    return MorphicResult.ErrorResult<ISetValueError>(new ISetValueError.ExceptionError(ex));
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }

        return MorphicResult.OkResult();
    }

    #endregion Set Value

    //

    #region Get/Set helper functions

    // Errors returned by the WaitFor* helpers: Timeout when the budget expires, ExceptionError
    // when an underlying WinRT call throws. Kept private to SettingItemProxy -- callers translate
	// these into theirerror union (e.g. IGetValueError, ISetValueError).
    private interface IWaitForSettingEventError
    {
        public record ExceptionError(Exception Ex) : IWaitForSettingEventError;
        public record Timeout : IWaitForSettingEventError;
    }

    private async Task<MorphicResult<MorphicUnit, IWaitForSettingEventError>> WaitForIsEnabledEventAsync(int timeoutInMilliseconds, bool alsoWaitForApplicable = false)
    {
        using var propertyChangedWaitHandle = new AutoResetEvent(false);
        var propertyChangedHandler = new Windows.Foundation.TypedEventHandler<object, string>((object sender, string args) =>
        {
            switch (args)
            {
                case "IsApplicable":
                    if (alsoWaitForApplicable == true)
                    {
                        propertyChangedWaitHandle.Set();
                    }
                    break;
                case "IsEnabled":
                    propertyChangedWaitHandle.Set();
                    break;
                default:
                    break;
            }
        });
        var isWatchingForPropertyChangedEvent = false;

        // Returns Ok(true) when the condition is satisfied; Ok(false) when not; ExceptionError
        // when the IsApplicable/IsEnabled property reads throw. We surface the exception (rather
        // than silently treating it as "not satisfied") so a failing WinRT proxy can't loop us
        // indefinitely until timeout.
        MorphicResult<bool, IWaitForSettingEventError> CheckIsConditionSatisfied()
        {
            bool isApplicable;
            bool isEnabled;
            try
            {
                (isApplicable, isEnabled) = SettingItemDispatcher.Run(() => (_settingItem.IsApplicable, _settingItem.IsEnabled));
            }
            catch (Exception ex)
            {
                return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.ExceptionError(ex));
            }

            var conditionSatisfied = false;
            //
            // check our base condition
            if (isEnabled == true)
            {
                conditionSatisfied = true;
            }
            //
            // check our additional (optional) conditions
            if (alsoWaitForApplicable == true)
            {
                if (isApplicable == false)
                {
                    conditionSatisfied = false;
                }
            }

            return MorphicResult.OkResult(conditionSatisfied);
        }

        try
        {
            Stopwatch timeoutStopwatch = Stopwatch.StartNew();
            // NOTE: we use an infinite loop so that we can wait multiple times (if, for instance, we get events for only one of multiple states); it will terminate upon timeout in the
            //       worst-case scenario
            while (true)
            {
                // for every iteration of the loop, we check to see if the condition is satisfied
                var checkResult = CheckIsConditionSatisfied();
                if (checkResult.IsError)
                {
                    return MorphicResult.ErrorResult(checkResult.Error!);
                }
                if (checkResult.Value == true)
                {
                    break;
                }

                // if we're not already watching for the propert(ies) to change, wire up an event handler now
                if (isWatchingForPropertyChangedEvent == false)
                {
                    try
                    {
                        SettingItemDispatcher.Run(() => { _settingItem.SettingChanged += propertyChangedHandler; });
                    }
                    catch (Exception ex)
                    {
                        return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.ExceptionError(ex));
                    }
                    isWatchingForPropertyChangedEvent = true;

                    // check to see if the condition is satisfied one more time, just in case the condition became satisfied at the same time we were setting up the event
                    var recheckResult = CheckIsConditionSatisfied();
                    if (recheckResult.IsError)
                    {
                        return MorphicResult.ErrorResult(recheckResult.Error!);
                    }
                    if (recheckResult.Value == true)
                    {
                        break;
                    }
                }

                // NOTE: if we reach this point, we are not ready yet; we need to wait for the corresponding event(s) to change
                var remainingTimeout = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
                if (remainingTimeout == 0)
                {
                    return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.Timeout());
                }

                // wait for the IsApplicable/IsEnabled event handler to fire (or for our timeout to expire, whichever comes first)
                TaskCompletionSource<bool>? taskCompletionSource = new TaskCompletionSource<bool>();
                //
                // NOTE: we treat taskCompletionSource as nullable here just in case it the delegate gets called after the function completes (which should not happen, but we saw a null taskCompletionSource once in testing)
                var waitHandleRegistration = ThreadPool.RegisterWaitForSingleObject(propertyChangedWaitHandle, delegate { taskCompletionSource?.SetResult(true); }, null, remainingTimeout, true);
                try
                {
                    _ = await taskCompletionSource!.Task.WaitAsync(new TimeSpan(0, 0, 0, 0, remainingTimeout));
                }
                catch (TimeoutException)
                {
                    // swallow the TimeoutException; we'll capture this timeout in the next loop iteration
                    //return MorphicResult.ErrorResult(MorphicTimeoutError.Timeout);
                }
                finally
                {
                    // NOTE: we do not need to signal any wait handle when we unregister the wait handle registration (i.e. the waitObject param is null)
                    waitHandleRegistration.Unregister(null);
                }
            }

            return MorphicResult.OkResult();
        }
        finally
        {
            if (isWatchingForPropertyChangedEvent == true)
            {
                // Unsubscribe inside try/catch so a failure here can't mask the actual result --
                // we already have a result to return and the wait is finishing one way or another.
                try
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged -= propertyChangedHandler; });
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"[SettingItemProxy.WaitForIsEnabledEventAsync] SettingChanged unsubscribe failed: {ex.Message}");
                }
                isWatchingForPropertyChangedEvent = false;
            }
        }
    }

    // Waits until reading `name` returns a value equal to `expectedValue`, OR until
    // timeoutInMilliseconds expires. Same shape as WaitForIsEnabledEventAsync: check the
    // condition first; if not satisfied, subscribe to SettingChanged, recheck (close race),
    // then loop on event signal until satisfied or timed out.
    //
    // The event filter only signals on the "Value" SettingChanged subkey -- other property
    // changes (IsApplicable, IsEnabled) don't wake the loop. The read itself is guarded by
    // try/catch and propagates the exception as IWaitForSettingEventError.ExceptionError --
    // we surface read failures rather than spinning silently until timeout, so a broken proxy
    // or genuinely failing GetValue can't masquerade as ValueDidNotApplyAfterSet.
    //
    // Equality uses System.Object.Equals (the static one, which handles nulls). Works correctly
    // for the boxed primitive types SettingItems carry in practice (bool, int, string, double).
    // If a future setting carries a value type whose Equals override doesn't reflect "value
    // equality" the way we expect, we'd need a comparer parameter -- not currently needed.
    private async Task<MorphicResult<MorphicUnit, IWaitForSettingEventError>> WaitForValueToEqualAsync(string name, object expectedValue, int timeoutInMilliseconds)
    {
        using var propertyChangedWaitHandle = new AutoResetEvent(false);
        var propertyChangedHandler = new Windows.Foundation.TypedEventHandler<object, string>((object sender, string args) =>
        {
            if (args == "Value")
            {
                propertyChangedWaitHandle.Set();
            }
        });
        var isWatchingForPropertyChangedEvent = false;

        MorphicResult<bool, IWaitForSettingEventError> CheckIsConditionSatisfied()
        {
            object? currentValue;
            try
            {
                currentValue = SettingItemDispatcher.Run(() => _settingItem.GetValue(name));
            }
            catch (Exception ex)
            {
                return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.ExceptionError(ex));
            }
            return MorphicResult.OkResult(object.Equals(currentValue, expectedValue));
        }

        try
        {
            Stopwatch timeoutStopwatch = Stopwatch.StartNew();
            while (true)
            {
                var checkResult = CheckIsConditionSatisfied();
                if (checkResult.IsError == true)
                {
                    return MorphicResult.ErrorResult(checkResult.Error!);
                }
                if (checkResult.Value == true)
                {
                    break;
                }

                if (isWatchingForPropertyChangedEvent == false)
                {
                    try
                    {
                        SettingItemDispatcher.Run(() => { _settingItem.SettingChanged += propertyChangedHandler; });
                    }
                    catch (Exception ex)
                    {
                        return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.ExceptionError(ex));
                    }
                    isWatchingForPropertyChangedEvent = true;

                    // Recheck once after subscribing in case the value settled between the first
                    // check and our subscription wiring up (otherwise we could wait forever on a
                    // signal that already fired).
                    var recheckResult = CheckIsConditionSatisfied();
                    if (recheckResult.IsError == true)
                    {
                        return MorphicResult.ErrorResult(recheckResult.Error!);
                    }
                    if (recheckResult.Value == true)
                    {
                        break;
                    }
                }

                var remainingTimeout = (int)Math.Max(timeoutInMilliseconds - timeoutStopwatch.ElapsedMilliseconds, 0);
                if (remainingTimeout == 0)
                {
                    return MorphicResult.ErrorResult<IWaitForSettingEventError>(new IWaitForSettingEventError.Timeout());
                }

                TaskCompletionSource<bool>? taskCompletionSource = new TaskCompletionSource<bool>();
                var waitHandleRegistration = ThreadPool.RegisterWaitForSingleObject(propertyChangedWaitHandle, delegate { taskCompletionSource?.SetResult(true); }, null, remainingTimeout, true);
                try
                {
                    _ = await taskCompletionSource!.Task.WaitAsync(new TimeSpan(0, 0, 0, 0, remainingTimeout));
                }
                catch (TimeoutException)
                {
                    // swallow; the next loop iteration's remainingTimeout=0 check returns Timeout
                }
                finally
                {
                    waitHandleRegistration.Unregister(null);
                }
            }

            return MorphicResult.OkResult();
        }
        finally
        {
            if (isWatchingForPropertyChangedEvent == true)
            {
                // Unsubscribe inside try/catch so a failure here can't mask the actual result --
                // we already have a result to return and the wait is finishing one way or another.
                try
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged -= propertyChangedHandler; });
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"[SettingItemProxy.WaitForValueToEqualAsync] SettingChanged unsubscribe failed: {ex.Message}");
                }
            }
        }
    }

    #endregion Get/Set helper functions

    //

    #region Event handlers

    /// <summary>
    /// Raised when the WinRT SettingItem's IsApplicable property changes. Handler callbacks run
    /// on a Task.Run-dispatched ThreadPool thread (NOT the UI thread). The native SettingChanged
    /// signal arrives on the SettingItemDispatcher's STA worker thread first and is fanned out
    /// to subscribers from a single Task.Run for isolation.
    /// </summary>
    /// <exception cref="System.Exception">
    /// Subscribing or unsubscribing may throw (typically COMException) if the underlying WinRT
    /// SettingChanged += / -= call fails. On subscribe failure the user's handler is NOT added;
    /// on unsubscribe failure the user's handler IS removed but downstream WinRT cleanup may
    /// have failed. Callers must catch.
    /// </exception>
    public event EventHandler IsApplicableChanged
    {
        add
        {
            lock (_eventsLock)
            {
                if (_settingsChangedEventHandlerIsSubscribed == false)
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged += _settingItem_SettingChanged; });
                    _settingsChangedEventHandlerIsSubscribed = true;
                }
                _isApplicableChanged += value;
            }
        }
        remove
        {
            lock (_eventsLock)
            {
                _isApplicableChanged -= value;
            }

            this.UnsubscribeSettingChangedEventHandlerIfEventsAreEmpty();
        }
    }

    /// <summary>
    /// Raised when the WinRT SettingItem's IsEnabled property changes. Handler callbacks run
    /// on a Task.Run-dispatched ThreadPool thread (NOT the UI thread). The native
    /// SettingChanged signal arrives on the SettingItemDispatcher's STA worker thread first
    /// and is fanned out to subscribers from a single Task.Run for isolation.
    /// </summary>
    /// <exception cref="System.Exception">
    /// Subscribing or unsubscribing may throw (typically COMException) if the underlying WinRT
    /// SettingChanged += / -= call fails. On subscribe failure the user's handler is NOT added;
    /// on unsubscribe failure the user's handler IS removed but downstream WinRT cleanup may
    /// have failed. Callers must catch.
    /// </exception>
    public event EventHandler IsEnabledChanged
    {
        add
        {
            lock (_eventsLock)
            {
                if (_settingsChangedEventHandlerIsSubscribed == false)
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged += _settingItem_SettingChanged; });
                    _settingsChangedEventHandlerIsSubscribed = true;
                }
                _isEnabledChanged += value;
            }
        }
        remove
        {
            lock (_eventsLock)
            {
                _isEnabledChanged -= value;
            }

            this.UnsubscribeSettingChangedEventHandlerIfEventsAreEmpty();
        }
    }
    //
    /// <summary>
    /// Raised when the WinRT SettingItem's Value changes. Handler callbacks run on a
    /// Task.Run-dispatched ThreadPool thread (NOT the UI thread). The native SettingChanged
    /// signal arrives on the SettingItemDispatcher's STA worker thread first and is fanned out
    /// to subscribers from a single Task.Run for isolation. The event carries no payload;
    /// subscribers should re-read the current value via GetValueAsync if needed.
    /// </summary>
    /// <exception cref="System.Exception">
    /// Subscribing or unsubscribing may throw (typically COMException) if the underlying WinRT
    /// SettingChanged += / -= call fails. On subscribe failure the user's handler is NOT added;
    /// on unsubscribe failure the user's handler IS removed but downstream WinRT cleanup may
    /// have failed. Callers must catch.
    /// </exception>
    public event EventHandler ValueChanged
    {
        add
        {
            lock (_eventsLock)
            {
                if (_settingsChangedEventHandlerIsSubscribed == false)
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged += _settingItem_SettingChanged; });
                    _settingsChangedEventHandlerIsSubscribed = true;
                }
                _valueChanged += value;
            }
        }
        remove
        {
            lock (_eventsLock)
            {
                _valueChanged -= value;
            }

            this.UnsubscribeSettingChangedEventHandlerIfEventsAreEmpty();
        }
    }

    private void UnsubscribeSettingChangedEventHandlerIfEventsAreEmpty()
    {
        lock (_eventsLock)
        {
            var isApplicableChangedIsEmpty = (_isApplicableChanged is null || _isApplicableChanged!.GetInvocationList().Length == 0);
            var isEnabledChangedIsEmpty = (_isEnabledChanged is null || _isEnabledChanged!.GetInvocationList().Length == 0);
            var valueChangedIsEmpty = (_valueChanged is null || _valueChanged!.GetInvocationList().Length == 0);

            if (isApplicableChangedIsEmpty == true && isEnabledChangedIsEmpty == true && valueChangedIsEmpty == true)
            {
                // Reset the flag in finally so it stays consistent even if the WinRT unsubscribe
                // throws -- otherwise a future subscriber would skip the WinRT subscribe (thinking
                // we're still wired up) and silently get no events. The throw still propagates to
                // the caller per the event's documented contract.
                try
                {
                    SettingItemDispatcher.Run(() => { _settingItem.SettingChanged -= _settingItem_SettingChanged; });
                }
                finally
                {
                    _settingsChangedEventHandlerIsSubscribed = false;
                }
            }
        }
    }

    private void _settingItem_SettingChanged(object sender, string args)
    {
        // We arrive here on the SettingItemDispatcher's STA worker thread (because the
        // SettingChanged += registration happened there). Hand subscribers off to a single
        // ThreadPool task so:
        //   * we return quickly to the worker, freeing it for the next dispatched call
        //   * subscribers run isolated from each other via per-handler try/catch
        //   * we don't spawn N tasks per N subscribers per event raise (the previous shape)
        EventHandler? source = args switch
        {
            "IsApplicable" => _isApplicableChanged,
            "IsEnabled" => _isEnabledChanged,
            "Value" => _valueChanged,
            _ => null,
        };
        SettingItemProxy.DispatchEventToSubscribers(source, sender);
    }

    // Single ThreadPool task that fans out to every current subscriber of `source`, isolating
    // each via try/catch so one throwing handler can't suppress the others or surface as an
    // unobserved-task exception. No-ops if there are no subscribers.
    private static void DispatchEventToSubscribers(EventHandler? source, object sender)
    {
        var invocationList = source?.GetInvocationList();
        if (invocationList is null || invocationList.Length == 0)
        {
            return;
        }

        _ = Task.Run(() =>
        {
            foreach (EventHandler subscriber in invocationList)
            {
                try
                {
                    subscriber.Invoke(sender, EventArgs.Empty);
                }
                catch (Exception ex)
                {
                    Debug.WriteLine($"[SettingItemProxy] SettingChanged subscriber threw: {ex.Message}");
                }
            }
        });
    }

    #endregion Event handlers

    //

    #region Static helpers

    public interface IGetSettingItemValueError
    {
        public record ExceptionError(Exception Ex) : IGetSettingItemValueError;
        public record SettingItemIsNull : IGetSettingItemValueError;
        public record Timeout : IGetSettingItemValueError;
        public record TypeMismatch : IGetSettingItemValueError;
    }
    //
    public async static Task<MorphicResult<T?, IGetSettingItemValueError>> GetSettingItemValueAsync<T>(SettingItemProxy? settingItem, TimeSpan? timeout = null) where T : struct
    {
        return await SettingItemProxy.GetSettingItemValueAsync<T>(settingItem, "Value", timeout);
    }
    //
    public async static Task<MorphicResult<T?, IGetSettingItemValueError>> GetSettingItemValueAsync<T>(SettingItemProxy? settingItem, string name, TimeSpan? timeout = null) where T : struct
    {
        // NOTE: for convenience, we let the caller pass in a nullable SettingItem
        if (settingItem is null)
        {
            return MorphicResult.ErrorResult<IGetSettingItemValueError>(new IGetSettingItemValueError.SettingItemIsNull());
        }

        MorphicResult<T?, Morphic.WindowsNative.SystemSettings.SettingItemProxy.IGetValueError> getSettingResult;
        getSettingResult = await settingItem.GetValueAsync<T>(name, timeout);
        if (getSettingResult.IsError == true)
        {
            switch (getSettingResult.Error!)
            {
                case IGetValueError.ExceptionError(var ex):
                    {
                        return MorphicResult.ErrorResult<IGetSettingItemValueError>(new IGetSettingItemValueError.ExceptionError(ex));
                    }
                case IGetValueError.Timeout:
                    return MorphicResult.ErrorResult<IGetSettingItemValueError>(new IGetSettingItemValueError.Timeout());
                case IGetValueError.TypeMismatch:
                    return MorphicResult.ErrorResult<IGetSettingItemValueError>(new IGetSettingItemValueError.TypeMismatch());
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }
        var result = getSettingResult.Value;

        return MorphicResult.OkResult(result);
    }

    //

    public interface ISetSettingItemValueError
    {
        public record ExceptionError(Exception Ex) : ISetSettingItemValueError;
        public record SettingItemIsNull : ISetSettingItemValueError;
        //public record SetSettingItemValueError SettingNotApplicableOrNotEnabledAfterSet : ISetSettingItemValueError;
        public record Timeout : ISetSettingItemValueError;
        //public record TypeMismatch : ISetSettingItemValueError;
        public record ValueDidNotApplyAfterSet : ISetSettingItemValueError;
    }

    // NOTE: both the struct- and class-specific implementations of SetSettingItemValueAsync MUST be kept in sync!
    //
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, T value, TimeSpan? timeout = null, bool verifyAfterSet = true) where T : struct
    {
        return await SettingItemProxy.SetSettingItemValueAsync<T>(settingItem, "Value", value, timeout, verifyAfterSet);
    }
    //
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, string name, T value, TimeSpan? timeout = null, bool verifyAfterSet = true) where T : struct
    {
        return await SettingItemProxy.SetSettingItemValueAsObjectAsync(settingItem, name, value, timeout, verifyAfterSet);
    }

    // NOTE: both the struct and class-specific implementations of SetSettingItemValueAsync MUST be kept in sync!
    //
    // NOTE: this second implementation of SetSettingItemValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, T value, TimeSpan? timeout = null, bool verifyAfterSet = true, object? _ = null) where T : class
    {
        return await SettingItemProxy.SetSettingItemValueAsync<T>(settingItem, "Value", value, timeout, verifyAfterSet);
    }
    //
    // NOTE: this second implementation of SetSettingItemValueAsync (with the _ param allowing it to act as an overload) is a kludge so that C# will work with both Nullable value types and (already-traditionally-nullable) reference types
    public async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsync<T>(SettingItemProxy? settingItem, string name, T value, TimeSpan? timeout = null, bool verifyAfterSet = true, object? _ = null) where T : class
    {
        return await SettingItemProxy.SetSettingItemValueAsObjectAsync(settingItem, name, value, timeout, verifyAfterSet);
    }

    private async static Task<MorphicResult<MorphicUnit, ISetSettingItemValueError>> SetSettingItemValueAsObjectAsync(SettingItemProxy? settingItem, string name, object value, TimeSpan? timeout = null, bool verifyAfterSet = true)
    {
        // NOTE: for 'binding-style' convenience, we let the caller pass in a nullable SettingItem; they'll just get an error result in return, however
        if (settingItem is null)
        {
            return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.SettingItemIsNull());
        }

        MorphicResult<MorphicUnit, Morphic.WindowsNative.SystemSettings.SettingItemProxy.ISetValueError> setSettingResult;
        setSettingResult = await settingItem.SetValueAsObjectAsync(name, value, timeout, verifyAfterSet);
        if (setSettingResult.IsError == true)
        {
            switch (setSettingResult.Error!)
            {
                case ISetValueError.ExceptionError(var ex):
                    {
                        return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.ExceptionError(ex));
                    }
                case ISetValueError.Timeout:
                    return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.Timeout());
                case ISetValueError.ValueDidNotApplyAfterSet:
                    return MorphicResult.ErrorResult<ISetSettingItemValueError>(new ISetSettingItemValueError.ValueDidNotApplyAfterSet());
                default:
                    throw new MorphicUnhandledErrorException();
            }
        }

        return MorphicResult.OkResult();
    }

    #endregion Static helpers
}
