# Morphic for Windows (.NET Desktop)

# Documentation used in this pipeline:
# .NET pipelines docs: 
# - Build, test, and deploy: https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core
# - .NET pipelines tasks: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/
# Microsoft-hosted agents: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops
# - Windows 2022 components and version options: https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md
# .NET Core release versions: https://github.com/dotnet/core/blob/main/release-notes/releases-index.json
# .NET Core RIDs (including x86/x64/ARM64): https://docs.microsoft.com/en-us/dotnet/core/rid-catalog

# NOTE: we version the builds using the current date in the build # (and the current same-day build number as the revision/patch #)
# major.minor.YYDDD.RRR (where YY is the year; DDD is the day of year; where RRR is the build run # within the day, starting at one)
name: $(Year:yy)$(DayOfYear).$(Rev:r)

# build all release and dev builds (as well as check-ins to the master branch)
trigger:
  branches:
    include:
      - master
      - dev/*
      - release/*
#      - '*'

# build all check-ins to pull requests
pr:
  branches:
    include:
    - '*'
variables:
# Import all Amazon S3 upload credentials and settings
- group: 's3-public-bucket-upload'
# Import all the code-signing variables (from the Library)
- group: 'windows-code-sign'
- name: mainProject
  value: Morphic/Morphic.csproj
- name: projects
  value: |
         Morphic/Morphic.csproj
- name: buildConfiguration
  value: 'Release'
- name: versionBuildComponents
  value: '.$(Build.BuildNumber)'

stages:
  - stage: build
    jobs:
      - job: build
        pool:
          vmImage: 'windows-2025-v2026'
        steps:


        - task: UseDotNet@2
          displayName: 'Use .NET SDK 10.0.201'
          inputs:
            packageType: sdk
            version: 10.0.201
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - task: DotNetCoreCLI@2
          displayName: 'Install AzureSignTool 7.0.1'
          inputs:
            command: 'custom'
            custom: 'tool'
            arguments: 'install --global AzureSignTool --version 7.0.1'


        - powershell: |
            winget install --source winget --exact --id Microsoft.WindowsSDK.10.0.22621 --log $env:USERPROFILE/Desktop/sdk-install.log
          displayName: "Install Windows SDK v10.0.22621.0"
        
        # NOTE: although NuGet restore is traditional for msbuild-based builds (and 'dotnet restore' for 'dotnet build'-based builds), 'dotnet restore' works with both
        - task: DotNetCoreCLI@2
          displayName: 'dotnet restore'
          inputs:
            command: restore
            projects: '$(projects)'
        
        # Set a $(BUILD_TYPE) variable
        # NOTE: we could change the build type depending on the branch type/name, but we currently do "production builds" for all branches
        - bash: |
            BUILD_TYPE="Production"
            echo "##vso[task.setvariable variable=BUILD_TYPE]${BUILD_TYPE}"
          env:
            BRANCH: $(Build.SourceBranch)
            BRANCH_NAME: $(Build.SourceBranchName)

#        - task: Bash@3
#          displayName: "write build info"
#          env:
#            BRANCH: $(Build.SourceBranch)
#            BRANCH_NAME: $(Build.SourceBranchName)
#            BUILD_NUM: $(Build.BuildNumber)
#            COMMIT: $(Build.SourceVersion)
#          inputs:
#            targetType: 'filePath'
#            filePath: set-build-info.sh

        - task: MSBuild@1
          displayName: "Build Morphic Client (x64)"
          env:
            VERSIONBUILDCOMPONENTS: '$(versionBuildComponents)'             
          inputs:       
            solution: '$(Build.SourcesDirectory)\Morphic\Morphic.csproj'
            platform: 'x64'
            configuration: '$(buildConfiguration)'
            msbuildArguments: '/t:restore,build /p:BuildType=$(BUILD_TYPE) /p:RuntimeIdentifier=win-x64'

        - task: MSBuild@1
          displayName: "Publish Morphic Client (x64)"
          env:
            VERSIONBUILDCOMPONENTS: '$(versionBuildComponents)'             
          inputs:       
            solution: '$(Build.SourcesDirectory)\Morphic\Morphic.csproj'
            platform: 'x64'
            configuration: '$(buildConfiguration)'
            msbuildArguments: '/t:publish /p:BuildType=$(BUILD_TYPE) /p:RuntimeIdentifier=win-x64'

#        - task: CmdLine@2
#          inputs:
#            targetType: 'inline'
#            script: >
#              tree $(Build.SourcesDirectory)\Morphic.Client\bin /f
              
        - task: CmdLine@2
          displayName: 'sign morphic client exe (x64)'
          inputs:
            targetType: 'inline'
# NOTE: if we experience downtime with our cert provider's timestamp servers (which causes signing to fail), 
#       we can use the test server (production timestamps, but from a 2nd provider); note that we should NOT do
#       this for any public preview or release builds...only for internal testing or emergency scenarios.
#              -tr "$(TimestampUrl)"
#              -tr "$(TimestampUrl2)"
#              vs.
#              -tr "$(TestOnlyTimestampUrl)"
            script: >
              AzureSignTool sign
              -d Morphic
              -du "$(SigningURL)"
              -kvu "$(SigningVaultURL)"
              -kvi "$(SigningClientId)"
              -kvs "$(SigningClientSecret)"
              -kvt "$(AzureTenantId)"
              -kvc "$(SigningCertName)"
              -tr "$(TimestampUrl2)"
              -v
              $(Build.SourcesDirectory)\Morphic\bin\x64\$(buildConfiguration)\net10.0-windows10.0.22621.0\win-x64\publish\Morphic.exe

        - publish: $(System.DefaultWorkingDirectory)\Morphic\BuildVersion.txt
          displayName: "Cache build version number"
          artifact: build-version

        - powershell: |
            # Read the full version string from line 2 of BuildVersion.txt
            $version = (Get-Content "$(System.DefaultWorkingDirectory)\Morphic\BuildVersion.txt")[1].Trim()
            Write-Host "Using version: $version"
            # Update MorphicPackage's appmanifest with the version number before building it
            [xml]$manifest = Get-Content "$(System.DefaultWorkingDirectory)\Morphic (Package)\Package.appxmanifest"
            $manifest.Package.Identity.Version = $version
            $manifest.Save("$(System.DefaultWorkingDirectory)\Morphic (Package)\Package.appxmanifest")
          displayName: 'Assign version to package manifest'

        - task: MSBuild@1
          displayName: 'Build packaged app (x64)'
          inputs:
            solution: 'Morphic (Package)/Morphic (Package).wapproj'
            platform: 'x64'
            configuration: $(buildConfiguration)
            msbuildArguments: '/p:UapAppxPackageBuildMode=SideLoadOnly /p:AppxBundle=Never /p:AppxPackageOutput=$(Build.ArtifactStagingDirectory)\MorphicSetup-x64.msix /p:AppxPackageSigningEnabled=false'


        - task: CmdLine@2
          displayName: 'Sign MSIX (x64)'
          inputs:
            script: >
              AzureSignTool sign
              -d Morphic
              -du "$(SigningURL)"
              -kvu "$(SigningVaultURL)"
              -kvi "$(SigningClientId)"
              -kvt "$(AzureTenantId)"
              -kvs "$(SigningClientSecret)"
              -kvc "$(SigningCertName)"
              -tr "$(TimestampUrl2)"
              -v $(Build.ArtifactStagingDirectory)\MorphicSetup-x64.msix

        - task: PublishPipelineArtifact@1
          displayName: "Cache MSIX (x64) for upload"
          inputs:
            targetPath: $(Build.ArtifactStagingDirectory)\MorphicSetup-x64.msix
            artifactName: msix-x64
            artifactType: pipeline

  - stage: publish
    jobs:
      - job: publish
        pool:
          vmImage: "ubuntu-24.04"
        steps:
        - download: current
          artifact: build-version

#        - download: current
#          artifact: msi-x64

        - task: DownloadPipelineArtifact@2
          displayName: "Capture MSIX (x64) for upload"
          inputs:
            source: 'current'
            artifact: msix-x64
            path: msix-x64

        - task: Bash@3
          displayName: "Upload MSIs/MSIXs to S3"
          env:
              AWS_ACCESS_KEY_ID: $(accessKey)
              AWS_SECRET_ACCESS_KEY: $(secretKey)
              AWS_DEFAULT_REGION: $(region)
              BUCKET: $(bucket)
          inputs:
            targetType: 'inline'
            script: |
                    # automatically exit if any command returns an error exit code
                    set -e
                    # print all commands to the terminal output
                    set -x

                    echo "detected dev build"
                    S3_BUILD_OPERATING_SYSTEM="win"
                    S3_BUILD_TYPE="dev"
                    # expire dev builds after 7 days
                    EXTRA_ARGS="--expires $(date -d '+7 days' --iso-8601=seconds)"

                    S3_PUBLISHED_HTTP_URL="https://d23vryjv7k8eyb.cloudfront.net"

                    publishMsixInstaller() {
                      VERSION=$(sed -n 1p ${AGENT_BUILDDIRECTORY}/build-version/BuildVersion.txt | tr -d [:space:])
                      LOCAL_MSIX_SOURCE="${AGENT_BUILDDIRECTORY}/${LOCAL_MSIX_DIR}/${MSIX_NAME_BASE}.msix"
                      S3_MSIX_OBJECT_NAME="${S3_BUILD_OPERATING_SYSTEM}/${S3_BUILD_ARCHITECTURE}/${S3_BUILD_TYPE}/MorphicSetup-v${VERSION}-${S3_BUILD_TYPE}-${S3_BUILD_ARCHITECTURE}.msix"

                      # debug: output the contents of the build directory
                      ls -al ${AGENT_BUILDDIRECTORY}/${LOCAL_MSIX_DIR}
                      aws s3 cp $EXTRA_ARGS "${LOCAL_MSIX_SOURCE}" "s3://${BUCKET}/${S3_MSIX_OBJECT_NAME}"
                    }

                    publishMsiInstaller() {
                      VERSION=$(sed -n 1p ${AGENT_BUILDDIRECTORY}/build-version/BuildVersion.txt | tr -d [:space:])
                      ASSEMBLY_VERSION=$(sed -n 2p ${AGENT_BUILDDIRECTORY}/build-version/BuildVersion.txt | tr -d [:space:])
                      LOCAL_MSI_SOURCE="${AGENT_BUILDDIRECTORY}/${LOCAL_MSI_DIR}/${MSI_NAME_BASE}.msi"
                      LOCAL_APPCAST_SOURCE="${AGENT_BUILDDIRECTORY}/${MSI_NAME_BASE}-v${VERSION}.appcast.xml"
                      S3_MSI_OBJECT_NAME="${S3_BUILD_OPERATING_SYSTEM}/${S3_BUILD_ARCHITECTURE}/${S3_BUILD_TYPE}/${MSI_NAME_BASE}-v${VERSION}-${S3_BUILD_TYPE}-${S3_BUILD_ARCHITECTURE}.msi"
                      S3_APPCAST_OBJECT_NAME="${S3_BUILD_OPERATING_SYSTEM}/${S3_BUILD_ARCHITECTURE}/${S3_BUILD_TYPE}/${MSI_NAME_BASE}-v${VERSION}.appcast.xml"

                      cat > "${LOCAL_APPCAST_SOURCE}" <<EOF
                    <?xml version="1.0" encoding="utf-8"?>
                    <item>
                        <version>${ASSEMBLY_VERSION}</version>
                        <url>${S3_PUBLISHED_HTTP_URL}/${S3_MSI_OBJECT_NAME}</url>
                    </item>
                    EOF

                      echo ${S3_PUBLISHED_HTTP_URL}/${S3_APPCAST_OBJECT_NAME}
                      cat "${LOCAL_APPCAST_SOURCE}"

                      # debug: output the contents of the build directory
                      ls -al ${AGENT_BUILDDIRECTORY}
                      aws s3 cp $EXTRA_ARGS "${LOCAL_MSI_SOURCE}" "s3://${BUCKET}/${S3_MSI_OBJECT_NAME}"
                      aws s3 cp $EXTRA_ARGS "${LOCAL_APPCAST_SOURCE}" "s3://${BUCKET}/${S3_APPCAST_OBJECT_NAME}"
                    }

                    echo "Uploading MSIX (x64) to S3"
                    MSIX_NAME_BASE="MorphicSetup-x64"
                    # NOTE: "s/" is a temporary path requirement; we may also consider calling these folders just "x64" etc.
                    LOCAL_MSIX_DIR="s/msix-x64"
                    S3_BUILD_ARCHITECTURE="x64"
                    publishMsixInstaller

