// Copyright 2026 Raising the Floor - US, Inc.
//
// Licensed under the New BSD license. You may not use this file except in
// compliance with this License.
//
// You may obtain a copy of the License at
// https://github.com/raisingthefloor/morphic-windows/blob/master/LICENSE.txt
//
// The R&D leading to these results received funding from the:
// * Rehabilitation Services Administration, US Dept. of Education under
//   grant H421A150006 (APCP)
// * National Institute on Disability, Independent Living, and
//   Rehabilitation Research (NIDILRR)
// * Administration for Independent Living & Dept. of Education under grants
//   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
// * European Union's Seventh Framework Programme (FP7/2007-2013) grant
//   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
// * William and Flora Hewlett Foundation
// * Ontario Ministry of Research and Innovation
// * Canadian Foundation for Innovation
// * Adobe Foundation
// * Consumer Electronics Association Foundation

using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Morphic.Localization.SourceGenerator;

// Emits Morphic.Localization.Strings: one strongly typed static property per <data name="..."> key in
// the app's en-US Resources.resw (the authoritative key set). Each property resolves at runtime through
// MRT Core's default ResourceLoader (the "Resources" map), so a key that exists in es/ar/... returns the
// localized value and falls back to en-US otherwise. The en-US .resw reaches the generator as an
// AdditionalFile (wired in Morphic.csproj). Keeping the typed accessor generated (rather than
// hand-written) means a key added to / removed from the .resw is immediately reflected as a compile
// error or a new property -- the .resw stays the single source of truth.
[Generator(LanguageNames.CSharp)]
public sealed class StringsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var reswKeySets = context.AdditionalTextsProvider
            .Where(static additionalText =>
            {
                var normalizedPath = additionalText.Path.Replace('\\', '/').ToLowerInvariant();
                return normalizedPath.EndsWith("/en-us/resources.resw", StringComparison.Ordinal);
            })
            .Select(static (additionalText, cancellationToken) =>
            {
                var content = additionalText.GetText(cancellationToken)?.ToString() ?? string.Empty;
                return StringsGenerator.ParseResourceKeys(content);
            })
            .Collect();

        context.RegisterSourceOutput(reswKeySets, static (sourceProductionContext, keySets) =>
        {
            var keys = keySets
                .SelectMany(static keySet => keySet)
                .Distinct(StringComparer.Ordinal)
                .OrderBy(static key => key, StringComparer.Ordinal)
                .ToImmutableArray();
            var generatedSource = StringsGenerator.BuildStringsClass(keys);
            sourceProductionContext.AddSource("Strings.g.cs", SourceText.From(generatedSource, Encoding.UTF8));
        });
    }

    private static ImmutableArray<string> ParseResourceKeys(string reswContent)
    {
        if (string.IsNullOrWhiteSpace(reswContent) == true)
        {
            return ImmutableArray<string>.Empty;
        }

        try
        {
            var document = XDocument.Parse(reswContent);
            var rootElement = document.Root;
            if (rootElement is null)
            {
                return ImmutableArray<string>.Empty;
            }

            // <data name="..."> entries are in the default (empty) namespace; the <xsd:schema> header is
            // in the XSD namespace and is correctly skipped by this no-namespace element name.
            return rootElement.Elements("data")
                .Select(static dataElement => dataElement.Attribute("name")?.Value)
                .Where(static name => string.IsNullOrEmpty(name) == false)
                .Select(static name => name!)
                .ToImmutableArray();
        }
        catch (System.Xml.XmlException)
        {
            return ImmutableArray<string>.Empty;
        }
    }

    private static string BuildStringsClass(ImmutableArray<string> keys)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace Morphic.Localization;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Strongly typed access to the application's localized strings. GENERATED from");
        builder.AppendLine("/// Strings/en-US/Resources.resw by Morphic.Localization.SourceGenerator; do not edit by hand.");
        builder.AppendLine("/// Each property resolves through MRT Core's default ResourceLoader (the \"Resources\" map), so");
        builder.AppendLine("/// values follow the user's Windows language at runtime in both packaged and unpackaged builds.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine("internal static partial class Strings");
        builder.AppendLine("{");
        builder.AppendLine("    private static readonly global::Microsoft.Windows.ApplicationModel.Resources.ResourceLoader s_resourceLoader = new();");

        foreach (var key in keys)
        {
            var propertyName = StringsGenerator.ToPropertyName(key);
            builder.AppendLine();
            builder.AppendLine("    /// <summary>Localized resource \"" + StringsGenerator.EscapeForXmlDoc(key) + "\".</summary>");
            builder.AppendLine("    internal static string " + propertyName + " => s_resourceLoader.GetString(\"" + StringsGenerator.EscapeForStringLiteral(key) + "\");");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    // Turns a resource key into a valid C# identifier (e.g. "MorphicForWindows.Text" -> "MorphicForWindows_Text").
    private static string ToPropertyName(string key)
    {
        var builder = new StringBuilder(key.Length);
        foreach (var character in key)
        {
            builder.Append((char.IsLetterOrDigit(character) == true || character == '_') ? character : '_');
        }

        var identifier = builder.ToString();
        if (identifier.Length == 0)
        {
            return "_";
        }
        if (char.IsDigit(identifier[0]) == true)
        {
            return "_" + identifier;
        }
        return identifier;
    }

    private static string EscapeForStringLiteral(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string EscapeForXmlDoc(string value)
    {
        return value.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
    }
}
