//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.2.0.241111.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace WinRT
{

    internal sealed unsafe class _EventSource_global__Windows_Foundation_TypedEventHandler_object__string_ : global::ABI.WinRT.Interop.EventSource<global::Windows.Foundation.TypedEventHandler<object, string>>
    {
        private static readonly bool initialized = global::WinRT.GenericTypeInstantiations.Windows_Foundation_TypedEventHandler_2_object__String.EnsureInitialized();

        internal _EventSource_global__Windows_Foundation_TypedEventHandler_object__string_(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {
            _ = initialized;
        }

        protected override ObjectReferenceValue CreateMarshaler(global::Windows.Foundation.TypedEventHandler<object, string> handler) =>
        global::ABI.Windows.Foundation.TypedEventHandler<object, string>.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<object, string>> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::Windows.Foundation.TypedEventHandler<object, string>>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::Windows.Foundation.TypedEventHandler<object, string> GetEventInvoke()
            {
                return (object sender, string args) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, args);
                };
            }
        }
    }

    internal sealed unsafe class _EventSource_global__SystemSettings_DataModel_SettingsEnvironmentChangedHandler : global::ABI.WinRT.Interop.EventSource<global::SystemSettings.DataModel.SettingsEnvironmentChangedHandler>
    {


        internal _EventSource_global__SystemSettings_DataModel_SettingsEnvironmentChangedHandler(IObjectReference obj,
        delegate* unmanaged[Stdcall]<System.IntPtr, System.IntPtr, WinRT.EventRegistrationToken*, int> addHandler,
        delegate* unmanaged[Stdcall]<System.IntPtr, WinRT.EventRegistrationToken, int> removeHandler, int index) : base(obj, addHandler, removeHandler, index)
        {

        }

        protected override ObjectReferenceValue CreateMarshaler(global::SystemSettings.DataModel.SettingsEnvironmentChangedHandler handler) =>
        global::ABI.SystemSettings.DataModel.SettingsEnvironmentChangedHandler.CreateMarshaler2(handler);

        protected override global::ABI.WinRT.Interop.EventSourceState<global::SystemSettings.DataModel.SettingsEnvironmentChangedHandler> CreateEventSourceState() =>
        new EventState(ObjectReference.ThisPtr, Index);

        [global::WinRT.WinRTExposedType]
        private sealed class EventState : global::ABI.WinRT.Interop.EventSourceState<global::SystemSettings.DataModel.SettingsEnvironmentChangedHandler>
        {
            public EventState(System.IntPtr obj, int index)
            : base(obj, index)
            {
            }

            protected override global::SystemSettings.DataModel.SettingsEnvironmentChangedHandler GetEventInvoke()
            {
                return (global::SystemSettings.DataModel.ISettingsEnvironmentDatabase sender, string variableName) =>
                {
                    var targetDelegate = TargetDelegate;
                    if (targetDelegate is null)
                    {
                        return ;
                    }
                    targetDelegate.Invoke(sender, variableName);
                };
            }
        }
    }

}