//------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by cswinrt.exe version 2.2.0.241111.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace WinRT.GenericTypeInstantiations
{

    internal static class Windows_Foundation_IAsyncOperation_1_Boolean
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe bool GetResults(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            byte __retval = default;
            global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, byte*, int>**)ThisPtr)[8](ThisPtr, &__retval));
            global::System.GC.KeepAlive(_obj);
            return __retval != 0;
        }
        private static unsafe global::Windows.Foundation.AsyncOperationCompletedHandler<bool> get_Completed(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[7](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Boolean.EnsureInitialized();
                return global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<bool>.FromAbi(__retval);
            }
            finally
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<bool>.DisposeAbi(__retval);
            }
        }
        private static unsafe void put_Completed(IObjectReference _obj, global::Windows.Foundation.AsyncOperationCompletedHandler<bool> value)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __value = default;
            try
            {
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Boolean.EnsureInitialized();
                __value = global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<bool>.CreateMarshaler2(value);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__value)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__value);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.Windows.Foundation.IAsyncOperationMethods<bool, byte>.InitRcwHelper(&put_Completed,
            &get_Completed,
            &GetResults);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IVectorView_1_String
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe string GetAt(IObjectReference _obj, uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, IntPtr*, int>**)ThisPtr)[6](ThisPtr, index, &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalString.FromAbi(__retval);
            }
            finally
            {
                MarshalString.DisposeAbi(__retval);
            }
        }

        private static unsafe bool IndexOf(IObjectReference _obj, string value, out uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            uint __index = default;
            byte __retval = default;
            MarshalString.Pinnable __value = new(value);
            fixed(void* ___value = __value)
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint*, byte*, int>**)ThisPtr)[8](ThisPtr, MarshalString.GetAbi(ref __value), &__index, &__retval));
                global::System.GC.KeepAlive(_obj);
                index = __index;
                return __retval != 0;
            }
        }

        private static unsafe uint GetMany(IObjectReference _obj, uint startIndex, string[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalString.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = MarshalString.CreateMarshalerArray(items);
                (__items_length, __items_data) = MarshalString.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, startIndex, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                MarshalString.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                MarshalString.DisposeMarshalerArray(__items);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IReadOnlyListMethods<string, IntPtr>.InitRcwHelper(&GetAt,
            &IndexOf,
            &GetMany);
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterable_1_String.EnsureInitialized();
            return true;
        }
    }

    internal static class Windows_Foundation_TypedEventHandler_2_object__String
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe void Invoke(IObjectReference _obj, object sender, string args)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __sender = default;
            try
            {
                __sender = MarshalInspectable<object>.CreateMarshaler2(sender);
                MarshalString.Pinnable __args = new(args);
                fixed(void* ___args = __args)
                {
                    global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, IntPtr, int>**)ThisPtr)[3](ThisPtr, MarshalInspectable<object>.GetAbi(__sender), MarshalString.GetAbi(ref __args)));
                    global::System.GC.KeepAlive(_obj);
                }
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__sender);
            }
        }

        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_Invoke(IntPtr thisPtr, IntPtr sender, IntPtr args)
        {



            try
            {
                global::ABI.Windows.Foundation.TypedEventHandlerMethods<object, IntPtr, string, IntPtr>.Abi_Invoke(thisPtr, MarshalInspectable<object>.FromAbi(sender), MarshalString.FromAbi(args));

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }


        private unsafe static bool Init()
        {
            global::ABI.Windows.Foundation.TypedEventHandlerMethods<object, IntPtr, string, IntPtr>.InitRcwHelper(&Invoke);
            global::ABI.Windows.Foundation.TypedEventHandlerMethods<object, IntPtr, string, IntPtr>.InitCcw(&Do_Abi_Invoke);

            return true;
        }
    }

    internal static class Windows_Foundation_IAsyncOperation_1_Windows_Storage_StorageFile
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::Windows.Storage.StorageFile GetResults(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[8](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.Windows.Storage.StorageFile.FromAbi(__retval);
            }
            finally
            {
                global::ABI.Windows.Storage.StorageFile.DisposeAbi(__retval);
            }
        }
        private static unsafe global::Windows.Foundation.AsyncOperationCompletedHandler<global::Windows.Storage.StorageFile> get_Completed(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[7](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Storage_StorageFile.EnsureInitialized();
                return global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::Windows.Storage.StorageFile>.FromAbi(__retval);
            }
            finally
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::Windows.Storage.StorageFile>.DisposeAbi(__retval);
            }
        }
        private static unsafe void put_Completed(IObjectReference _obj, global::Windows.Foundation.AsyncOperationCompletedHandler<global::Windows.Storage.StorageFile> value)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __value = default;
            try
            {
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Storage_StorageFile.EnsureInitialized();
                __value = global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::Windows.Storage.StorageFile>.CreateMarshaler2(value);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__value)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__value);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.Windows.Foundation.IAsyncOperationMethods<global::Windows.Storage.StorageFile, IntPtr>.InitRcwHelper(&put_Completed,
            &get_Completed,
            &GetResults);

            return true;
        }
    }

    internal static class Windows_Foundation_IAsyncOperation_1_Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp_
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp> GetResults(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[8](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp.EnsureInitialized();
                return MarshalInterface<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>.DisposeAbi(__retval);
            }
        }
        private static unsafe global::Windows.Foundation.AsyncOperationCompletedHandler<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>> get_Completed(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[7](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp_.EnsureInitialized();
                return global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>.FromAbi(__retval);
            }
            finally
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>.DisposeAbi(__retval);
            }
        }
        private static unsafe void put_Completed(IObjectReference _obj, global::Windows.Foundation.AsyncOperationCompletedHandler<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>> value)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __value = default;
            try
            {
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp_.EnsureInitialized();
                __value = global::ABI.Windows.Foundation.AsyncOperationCompletedHandler<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>.CreateMarshaler2(value);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, int>**)ThisPtr)[6](ThisPtr, MarshalInspectable<object>.GetAbi(__value)));
                global::System.GC.KeepAlive(_obj);
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__value);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.Windows.Foundation.IAsyncOperationMethods<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>, IntPtr>.InitRcwHelper(&put_Completed,
            &get_Completed,
            &GetResults);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionAppLink
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::SystemSettings.DataModel.SettingsExtensionAppLink GetAt(IObjectReference _obj, uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, IntPtr*, int>**)ThisPtr)[6](ThisPtr, index, &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.FromAbi(__retval);
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.DisposeAbi(__retval);
            }
        }

        private static unsafe bool IndexOf(IObjectReference _obj, global::SystemSettings.DataModel.SettingsExtensionAppLink value, out uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __value = default;
            uint __index = default;
            byte __retval = default;
            try
            {
                __value = global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.CreateMarshaler2(value);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint*, byte*, int>**)ThisPtr)[8](ThisPtr, MarshalInspectable<object>.GetAbi(__value), &__index, &__retval));
                global::System.GC.KeepAlive(_obj);
                index = __index;
                return __retval != 0;
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__value);
            }
        }

        private static unsafe uint GetMany(IObjectReference _obj, uint startIndex, global::SystemSettings.DataModel.SettingsExtensionAppLink[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalInterfaceHelper<global::SystemSettings.DataModel.SettingsExtensionAppLink>.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.CreateMarshalerArray(items);
                (__items_length, __items_data) = global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, startIndex, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.DisposeMarshalerArray(__items);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IReadOnlyListMethods<global::SystemSettings.DataModel.SettingsExtensionAppLink, IntPtr>.InitRcwHelper(&GetAt,
            &IndexOf,
            &GetMany);
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterable_1_SystemSettings_DataModel_SettingsExtensionAppLink.EnsureInitialized();
            return true;
        }
    }

    internal static class Windows_Foundation_AsyncOperationCompletedHandler_1_Boolean
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_Invoke(IntPtr thisPtr, IntPtr asyncInfo, global::Windows.Foundation.AsyncStatus asyncStatus)
        {
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_IAsyncOperation_1_Boolean.EnsureInitialized();



            try
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<bool, byte>.Abi_Invoke(thisPtr, MarshalInterface<global::Windows.Foundation.IAsyncOperation<bool>>.FromAbi(asyncInfo), asyncStatus);

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }


        private unsafe static bool Init()
        {

            global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<bool, byte>.InitCcw(&Do_Abi_Invoke);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterable_1_String
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::System.Collections.Generic.IEnumerator<string> First(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterator_1_String.EnsureInitialized();
                return MarshalInterface<global::System.Collections.Generic.IEnumerator<string>>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::System.Collections.Generic.IEnumerator<string>>.DisposeAbi(__retval);
            }
        }


        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumerableMethods<string, IntPtr>.InitRcwHelper(&First);

            return true;
        }
    }

    internal static class Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Storage_StorageFile
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_Invoke(IntPtr thisPtr, IntPtr asyncInfo, global::Windows.Foundation.AsyncStatus asyncStatus)
        {
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_IAsyncOperation_1_Windows_Storage_StorageFile.EnsureInitialized();



            try
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<global::Windows.Storage.StorageFile, IntPtr>.Abi_Invoke(thisPtr, MarshalInterface<global::Windows.Foundation.IAsyncOperation<global::Windows.Storage.StorageFile>>.FromAbi(asyncInfo), asyncStatus);

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }


        private unsafe static bool Init()
        {

            global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<global::Windows.Storage.StorageFile, IntPtr>.InitCcw(&Do_Abi_Invoke);

            return true;
        }
    }

    internal static class Windows_Foundation_AsyncOperationCompletedHandler_1_Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp_
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        [UnmanagedCallersOnly(CallConvs = new[] { typeof(CallConvStdcall) })]
        private static unsafe int Do_Abi_Invoke(IntPtr thisPtr, IntPtr asyncInfo, global::Windows.Foundation.AsyncStatus asyncStatus)
        {
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_IAsyncOperation_1_Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp_.EnsureInitialized();



            try
            {
                global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>, IntPtr>.Abi_Invoke(thisPtr, MarshalInterface<global::Windows.Foundation.IAsyncOperation<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>>>.FromAbi(asyncInfo), asyncStatus);

            }
            catch (Exception __exception__)
            {
                global::WinRT.ExceptionHelpers.SetErrorInfo(__exception__);
                return global::WinRT.ExceptionHelpers.GetHRForException(__exception__);
            }
            return 0;
        }


        private unsafe static bool Init()
        {

            global::ABI.Windows.Foundation.AsyncOperationCompletedHandlerMethods<global::System.Collections.Generic.IReadOnlyList<global::SystemSettings.DataModel.SettingsExtensionApp>, IntPtr>.InitCcw(&Do_Abi_Invoke);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IVectorView_1_SystemSettings_DataModel_SettingsExtensionApp
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::SystemSettings.DataModel.SettingsExtensionApp GetAt(IObjectReference _obj, uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, IntPtr*, int>**)ThisPtr)[6](ThisPtr, index, &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.SystemSettings.DataModel.SettingsExtensionApp.FromAbi(__retval);
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.DisposeAbi(__retval);
            }
        }

        private static unsafe bool IndexOf(IObjectReference _obj, global::SystemSettings.DataModel.SettingsExtensionApp value, out uint index)
        {
            var ThisPtr = _obj.ThisPtr;

            ObjectReferenceValue __value = default;
            uint __index = default;
            byte __retval = default;
            try
            {
                __value = global::ABI.SystemSettings.DataModel.SettingsExtensionApp.CreateMarshaler2(value);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr, uint*, byte*, int>**)ThisPtr)[8](ThisPtr, MarshalInspectable<object>.GetAbi(__value), &__index, &__retval));
                global::System.GC.KeepAlive(_obj);
                index = __index;
                return __retval != 0;
            }
            finally
            {
                MarshalInspectable<object>.DisposeMarshaler(__value);
            }
        }

        private static unsafe uint GetMany(IObjectReference _obj, uint startIndex, global::SystemSettings.DataModel.SettingsExtensionApp[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalInterfaceHelper<global::SystemSettings.DataModel.SettingsExtensionApp>.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = global::ABI.SystemSettings.DataModel.SettingsExtensionApp.CreateMarshalerArray(items);
                (__items_length, __items_data) = global::ABI.SystemSettings.DataModel.SettingsExtensionApp.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, uint, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, startIndex, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.DisposeMarshalerArray(__items);
            }
        }



        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IReadOnlyListMethods<global::SystemSettings.DataModel.SettingsExtensionApp, IntPtr>.InitRcwHelper(&GetAt,
            &IndexOf,
            &GetMany);
            _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterable_1_SystemSettings_DataModel_SettingsExtensionApp.EnsureInitialized();
            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterable_1_SystemSettings_DataModel_SettingsExtensionAppLink
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionAppLink> First(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterator_1_SystemSettings_DataModel_SettingsExtensionAppLink.EnsureInitialized();
                return MarshalInterface<global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionAppLink>>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionAppLink>>.DisposeAbi(__retval);
            }
        }


        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumerableMethods<global::SystemSettings.DataModel.SettingsExtensionAppLink, IntPtr>.InitRcwHelper(&First);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterator_1_String
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe uint GetMany(IObjectReference _obj, string[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalString.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = MarshalString.CreateMarshalerArray(items);
                (__items_length, __items_data) = MarshalString.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                MarshalString.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                MarshalString.DisposeMarshalerArray(__items);
            }
        }
        private static unsafe string get_Current(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return MarshalString.FromAbi(__retval);
            }
            finally
            {
                MarshalString.DisposeAbi(__retval);
            }
        }




        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumeratorMethods<string, IntPtr>.InitRcwHelper(&get_Current,
            &GetMany);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterable_1_SystemSettings_DataModel_SettingsExtensionApp
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionApp> First(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                _ = global::WinRT.GenericTypeInstantiations.Windows_Foundation_Collections_IIterator_1_SystemSettings_DataModel_SettingsExtensionApp.EnsureInitialized();
                return MarshalInterface<global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionApp>>.FromAbi(__retval);
            }
            finally
            {
                MarshalInterface<global::System.Collections.Generic.IEnumerator<global::SystemSettings.DataModel.SettingsExtensionApp>>.DisposeAbi(__retval);
            }
        }


        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumerableMethods<global::SystemSettings.DataModel.SettingsExtensionApp, IntPtr>.InitRcwHelper(&First);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterator_1_SystemSettings_DataModel_SettingsExtensionAppLink
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe uint GetMany(IObjectReference _obj, global::SystemSettings.DataModel.SettingsExtensionAppLink[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalInterfaceHelper<global::SystemSettings.DataModel.SettingsExtensionAppLink>.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.CreateMarshalerArray(items);
                (__items_length, __items_data) = global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.DisposeMarshalerArray(__items);
            }
        }
        private static unsafe global::SystemSettings.DataModel.SettingsExtensionAppLink get_Current(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.FromAbi(__retval);
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionAppLink.DisposeAbi(__retval);
            }
        }




        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumeratorMethods<global::SystemSettings.DataModel.SettingsExtensionAppLink, IntPtr>.InitRcwHelper(&get_Current,
            &GetMany);

            return true;
        }
    }

    internal static class Windows_Foundation_Collections_IIterator_1_SystemSettings_DataModel_SettingsExtensionApp
    {
        private static bool Initialized { get; } = Init();

        public static bool EnsureInitialized() => Initialized;


        private static unsafe uint GetMany(IObjectReference _obj, global::SystemSettings.DataModel.SettingsExtensionApp[] items)
        {
            var ThisPtr = _obj.ThisPtr;

            MarshalInterfaceHelper<global::SystemSettings.DataModel.SettingsExtensionApp>.MarshalerArray __items = default;
            int __items_length = default;
            IntPtr __items_data = default;
            uint __retval = default;
            try
            {
                __items = global::ABI.SystemSettings.DataModel.SettingsExtensionApp.CreateMarshalerArray(items);
                (__items_length, __items_data) = global::ABI.SystemSettings.DataModel.SettingsExtensionApp.GetAbiArray(__items);
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, int, IntPtr, uint*, int>**)ThisPtr)[9](ThisPtr, __items_length, __items_data, &__retval));
                global::System.GC.KeepAlive(_obj);
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.CopyAbiArray(items, (__items_length, __items_data));
                return __retval;
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.DisposeMarshalerArray(__items);
            }
        }
        private static unsafe global::SystemSettings.DataModel.SettingsExtensionApp get_Current(IObjectReference _obj)
        {
            var ThisPtr = _obj.ThisPtr;

            IntPtr __retval = default;
            try
            {
                global::WinRT.ExceptionHelpers.ThrowExceptionForHR((*(delegate* unmanaged[Stdcall]<IntPtr, IntPtr*, int>**)ThisPtr)[6](ThisPtr, &__retval));
                global::System.GC.KeepAlive(_obj);
                return global::ABI.SystemSettings.DataModel.SettingsExtensionApp.FromAbi(__retval);
            }
            finally
            {
                global::ABI.SystemSettings.DataModel.SettingsExtensionApp.DisposeAbi(__retval);
            }
        }




        private unsafe static bool Init()
        {
            global::ABI.System.Collections.Generic.IEnumeratorMethods<global::SystemSettings.DataModel.SettingsExtensionApp, IntPtr>.InitRcwHelper(&get_Current,
            &GetMany);

            return true;
        }
    }

}