//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morphic.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morphic.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream LoginAnnounce {
            get {
                return ResourceManager.GetStream("LoginAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find settings, sign in/out, customize buttons, move settings, and more..
        /// </summary>
        internal static string QuickStrip_Advanced_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Advanced_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the Morphic Menu.
        /// </summary>
        internal static string QuickStrip_Advanced_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Advanced_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string QuickStrip_Clipboard_Copy_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Clipboard_Copy_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string QuickStrip_Clipboard_Paste_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Clipboard_Paste_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard.
        /// </summary>
        internal static string QuickStrip_Clipboard_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Clipboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QuickStrip_ColorFilters_Off_Title {
            get {
                return ResourceManager.GetString("QuickStrip_ColorFilters_Off_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QuickStrip_ColorFilters_On_Title {
            get {
                return ResourceManager.GetString("QuickStrip_ColorFilters_On_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes colors to adapt to color vision differences. To choose type, right-click on button..
        /// </summary>
        internal static string QuickStrip_Colors_Color_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Color_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Color Blindness filters on and off.
        /// </summary>
        internal static string QuickStrip_Colors_Color_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Color_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Vision.
        /// </summary>
        internal static string QuickStrip_Colors_Color_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Color_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string QuickStrip_Colors_Color_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Color_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast on, off.
        /// </summary>
        internal static string QuickStrip_Colors_Contrast_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Contrast_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast.
        /// </summary>
        internal static string QuickStrip_Colors_Contrast_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Contrast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change settings, right-click on button..
        /// </summary>
        internal static string QuickStrip_Colors_Dark_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Dark_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Dark Mode on and off.
        /// </summary>
        internal static string QuickStrip_Colors_Dark_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Dark_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        internal static string QuickStrip_Colors_Dark_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Dark_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string QuickStrip_Colors_Dark_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Dark_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night Light.
        /// </summary>
        internal static string QuickStrip_Colors_Night_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Night_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string QuickStrip_Colors_Night_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Night_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrast &amp; color.
        /// </summary>
        internal static string QuickStrip_Colors_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Colors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_Contrast_Off_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Contrast off.
        /// </summary>
        internal static string QuickStrip_Contrast_Off_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QuickStrip_Contrast_Off_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can make the screen easier to read. To change settings, right-click on button..
        /// </summary>
        internal static string QuickStrip_Contrast_On_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Contrast on.
        /// </summary>
        internal static string QuickStrip_Contrast_On_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QuickStrip_Contrast_On_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string QuickStrip_Contrast_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QuickStrip_DarkMode_Off_Title {
            get {
                return ResourceManager.GetString("QuickStrip_DarkMode_Off_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QuickStrip_DarkMode_On_Title {
            get {
                return ResourceManager.GetString("QuickStrip_DarkMode_On_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change Magnifier settings, right-click on button..
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns off Magnifier.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Magnifier.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier follows your mouse. Your mouse can click through the box..
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns on a Magnifying lens.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Magnifier.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        internal static string QuickStrip_Magnifier_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_NightMode_Off_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_Off_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns the Night Light feature off.
        /// </summary>
        internal static string QuickStrip_NightMode_Off_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_Off_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QuickStrip_NightMode_Off_Title {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_Off_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduces eye strain and makes it easier to fall asleep at night..
        /// </summary>
        internal static string QuickStrip_NightMode_On_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_On_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns the Night Light feature on.
        /// </summary>
        internal static string QuickStrip_NightMode_On_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_On_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QuickStrip_NightMode_On_Title {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_On_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night mode.
        /// </summary>
        internal static string QuickStrip_NightMode_Title {
            get {
                return ResourceManager.GetString("QuickStrip_NightMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text to be read. Then click play button to read. To change settings, right-click on button..
        /// </summary>
        internal static string QuickStrip_Reader_Start_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Start_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reads text that is selected.
        /// </summary>
        internal static string QuickStrip_Reader_Start_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Start_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Selected Text.
        /// </summary>
        internal static string QuickStrip_Reader_Start_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Start_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change voice and speed settings, right-click on either button..
        /// </summary>
        internal static string QuickStrip_Reader_Stop_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Stop_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops reading.
        /// </summary>
        internal static string QuickStrip_Reader_Stop_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Stop_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Reading Select Text.
        /// </summary>
        internal static string QuickStrip_Reader_Stop_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Stop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Selected.
        /// </summary>
        internal static string QuickStrip_Reader_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes everything on the screen larger..
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases Text Size everywhere.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size cannot go bigger.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes everything on the screen smaller..
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases Text Size everywhere.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size cannot go smaller.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string QuickStrip_Snip_Button_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Snip_Button_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Copy. Then click and drag mouse to take picture. Paste into any document..
        /// </summary>
        internal static string QuickStrip_Snip_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Snip_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Takes a picture of a selected part of the screen.
        /// </summary>
        internal static string QuickStrip_Snip_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Snip_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip a copy of part of screen.
        /// </summary>
        internal static string QuickStrip_Snip_Name {
            get {
                return ResourceManager.GetString("QuickStrip_Snip_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snip.
        /// </summary>
        internal static string QuickStrip_Snip_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Snip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes all sounds quieter..
        /// </summary>
        internal static string QuickStrip_Volume_Down_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreases the volume.
        /// </summary>
        internal static string QuickStrip_Volume_Down_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_Volume_Down_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume cannot go quieter.
        /// </summary>
        internal static string QuickStrip_Volume_Down_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes your speakers - but does NOT mute your microphone..
        /// </summary>
        internal static string QuickStrip_Volume_Mute_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutes all sounds from your computer.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Mute off - allowing sounds to come from your computer again..
        /// </summary>
        internal static string QuickStrip_Volume_Mute_MutedMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_MutedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmutes sounds.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_MutedTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_MutedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string QuickStrip_Volume_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turns Mute off - allowing sounds to come from your computer again..
        /// </summary>
        internal static string QuickStrip_Volume_Unmute_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Unmute_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmutes sounds.
        /// </summary>
        internal static string QuickStrip_Volume_Unmute_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Unmute_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes all sounds louder..
        /// </summary>
        internal static string QuickStrip_Volume_Up_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the volume.
        /// </summary>
        internal static string QuickStrip_Volume_Up_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuickStrip_Volume_Up_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume cannot go louder.
        /// </summary>
        internal static string QuickStrip_Volume_Up_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_LimitTitle", resourceCulture);
            }
        }
    }
}
