//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Morphic.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Morphic.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream LoginAnnounce {
            get {
                return ResourceManager.GetStream("LoginAnnounce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize buttons and take your settings with you anywhere.
        /// </summary>
        internal static string QuickStrip_Advanced_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Advanced_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Features.
        /// </summary>
        internal static string QuickStrip_Advanced_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Advanced_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make it harder to distinguish items.
        /// </summary>
        internal static string QuickStrip_Contrast_Off_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off High Contrast.
        /// </summary>
        internal static string QuickStrip_Contrast_Off_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string QuickStrip_Contrast_Off_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Off_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make it easier to distinguish items.
        /// </summary>
        internal static string QuickStrip_Contrast_On_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On High Contrast.
        /// </summary>
        internal static string QuickStrip_Contrast_On_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string QuickStrip_Contrast_On_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_On_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        internal static string QuickStrip_Contrast_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Contrast_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop magnifying part of the screen as you move.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide the Magnifying Glass.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string QuickStrip_Magnifier_Hide_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Hide_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnify a part of the screen as you move around.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a Magnifying Glass.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string QuickStrip_Magnifier_Show_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Show_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magnifier.
        /// </summary>
        internal static string QuickStrip_Magnifier_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Magnifier_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The computer will read aloud text you&apos;ve selected.
        /// </summary>
        internal static string QuickStrip_Reader_Start_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Start_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the Selected Text.
        /// </summary>
        internal static string QuickStrip_Reader_Start_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Start_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the computer from reading text aloud.
        /// </summary>
        internal static string QuickStrip_Reader_Stop_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Stop_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Reading.
        /// </summary>
        internal static string QuickStrip_Reader_Stop_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Stop_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Text.
        /// </summary>
        internal static string QuickStrip_Reader_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Reader_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all the text and icons bigger.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text and icons are as large as they can be.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Increase Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Bigger_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Bigger_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all the text and icons smaller.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text and icons are as small as they can be.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Decrease Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Smaller_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Smaller_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Size.
        /// </summary>
        internal static string QuickStrip_Resolution_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Resolution_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all the sounds quieter.
        /// </summary>
        internal static string QuickStrip_Volume_Down_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the Volume Down.
        /// </summary>
        internal static string QuickStrip_Volume_Down_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume is all the way down.
        /// </summary>
        internal static string QuickStrip_Volume_Down_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Turn the Volume Down.
        /// </summary>
        internal static string QuickStrip_Volume_Down_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Down_LimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off all sounds from the computer.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute All Sounds.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmute by pressing the volume up or down button.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_MutedMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_MutedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds Are Muted.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_MutedTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_MutedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        internal static string QuickStrip_Volume_Mute_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Mute_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string QuickStrip_Volume_Title {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make all the sounds louder.
        /// </summary>
        internal static string QuickStrip_Volume_Up_HelpMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn the Volume Up.
        /// </summary>
        internal static string QuickStrip_Volume_Up_HelpTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The volume is all the way up.
        /// </summary>
        internal static string QuickStrip_Volume_Up_LimitMessage {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_LimitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Turn the Volume Up.
        /// </summary>
        internal static string QuickStrip_Volume_Up_LimitTitle {
            get {
                return ResourceManager.GetString("QuickStrip_Volume_Up_LimitTitle", resourceCulture);
            }
        }
    }
}
