name: Download from Crowdin

on: [ workflow_dispatch ]

permissions:
  contents: write
  pull-requests: write

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@v2
      with:
        crowdin_branch_name: morphic-windows

        upload_sources: false
        upload_translations: false

        download_translations: true
        localization_branch_name: l10n_crowdin_action
        create_pull_request: true

        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
