// Copyright 2020-2026 Raising the Floor - US, Inc.
//
// Licensed under the New BSD license. You may not use this file except in
// compliance with this License.
//
// You may obtain a copy of the License at
// https://github.com/raisingthefloor/morphic-controls-lib-cs/blob/main/LICENSE.txt
//
// The R&D leading to these results received funding from the:
// * Rehabilitation Services Administration, US Dept. of Education under
//   grant H421A150006 (APCP)
// * National Institute on Disability, Independent Living, and
//   Rehabilitation Research (NIDILRR)
// * Administration for Independent Living & Dept. of Education under grants
//   H133E080022 (RERC-IT) and H133E130028/90RE5003-01-00 (UIITA-RERC)
// * European Union's Seventh Framework Programme (FP7/2007-2013) grant
//   agreement nos. 289016 (Cloud4all) and 610510 (Prosperity4All)
// * William and Flora Hewlett Foundation
// * Ontario Ministry of Research and Innovation
// * Canadian Foundation for Innovation
// * Adobe Foundation
// * Consumer Electronics Association Foundation

using System;
using System.Runtime.InteropServices;

namespace Morphic.Controls.TrayButton.Windows11;

// Gives the custom Win32 tray-button window a UI Automation identity (an accessible Name plus the
// Button control type) so Narrator and other assistive technologies can find and announce it. The
// window is a bare CreateWindowEx host with no standard control class, so without this provider it
// exposes no accessible name at all, even though it is Morphic's primary entry point. Wired in via
// the WM_GETOBJECT handler in TrayButtonNativeWindow.WndProc.
//
// The provider interfaces are hand-declared with classic [ComImport] (rather than generated by
// CsWin32) on purpose: implementing a provider means RETURNING VARIANT values from GetPropertyValue,
// and declaring the retval as a managed object with [MarshalAs(UnmanagedType.Struct)] lets the CLR
// marshal string/int/bool to VARIANT for us. That is far simpler and safer than populating the
// VARIANT struct that the CsWin32 projection would otherwise force on us.
internal sealed class TrayButtonUiaProvider : IRawElementProviderSimple
{
    // WM_GETOBJECT passes this value in lParam when a UI Automation client (not legacy MSAA) is requesting the provider.
    internal const int UiaRootObjectId = -25;

    private readonly Windows.Win32.Foundation.HWND _hwnd;
    private readonly Func<string?> _accessibleNameProvider;

    internal TrayButtonUiaProvider(Windows.Win32.Foundation.HWND hwnd, Func<string?> accessibleNameProvider)
    {
        _hwnd = hwnd;
        _accessibleNameProvider = accessibleNameProvider;
    }

    // We are an in-process (server-side) provider for our own window.
    public ProviderOptions ProviderOptions
    {
        get
        {
            return ProviderOptions.ServerSideProvider;
        }
    }

    // The tray button exposes no control patterns; a Name plus a control type is what AT discovery needs.
    public object? GetPatternProvider(int patternId)
    {
        return null;
    }

    // Return only the properties we explicitly override; returning null (VT_EMPTY) tells UIA to fall
    // back to the host provider (below), which supplies bounding rectangle, runtime id, process id, etc.
    public object? GetPropertyValue(int propertyId)
    {
        switch (propertyId)
        {
            case (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_NamePropertyId:
                return this._accessibleNameProvider() ?? string.Empty;
            case (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_ControlTypePropertyId:
                return (int)Windows.Win32.UI.Accessibility.UIA_CONTROLTYPE_ID.UIA_ButtonControlTypeId;
            case (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_IsControlElementPropertyId:
                return true;
            case (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_IsContentElementPropertyId:
                return true;
            case (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_IsEnabledPropertyId:
                return true;
            default:
                return null;
        }
    }

    // Delegate the properties we do not implement (bounding rectangle, runtime id, and so on) to the
    // default host provider that UI Automation maintains for any HWND.
    public IRawElementProviderSimple? HostRawElementProvider
    {
        get
        {
            try
            {
                var getHostProviderResult = TrayButtonUiaProvider.UiaHostProviderFromHwnd(_hwnd, out var hostProvider);
                if (getHostProviderResult.Failed == true)
                {
                    return null;
                }
                return hostProvider;
            }
            catch
            {
                return null;
            }
        }
    }

    // Hands the provider to UI Automation in response to a WM_GETOBJECT(lParam == UiaRootObjectId)
    // message; returns the LRESULT that the window procedure should return.
    internal static Windows.Win32.Foundation.LRESULT ReturnProviderForWmGetObject(Windows.Win32.Foundation.HWND hwnd, Windows.Win32.Foundation.WPARAM wParam, Windows.Win32.Foundation.LPARAM lParam, IRawElementProviderSimple provider)
    {
        return TrayButtonUiaProvider.UiaReturnRawElementProvider(hwnd, wParam, lParam, provider);
    }

    // Best-effort: tell listening AT clients that the accessible Name changed (for example, when the
    // button text flips between "Show MorphicBar" and "Hide MorphicBar"). Harmless when nothing is
    // listening (the call simply returns S_FALSE).
    internal static void RaiseNameChanged(IRawElementProviderSimple provider, string? previousName, string? newName)
    {
        try
        {
            _ = TrayButtonUiaProvider.UiaRaiseAutomationPropertyChangedEvent(provider, (int)Windows.Win32.UI.Accessibility.UIA_PROPERTY_ID.UIA_NamePropertyId, previousName ?? string.Empty, newName ?? string.Empty);
        }
        catch
        {
            // raising a property-change notification is purely advisory; never let it disrupt SetText
        }
    }

    // P/Invokes to UIAutomationCore.dll, hand-declared (not via CsWin32) so they accept our hand-rolled
    // IRawElementProviderSimple instead of the VARIANT-based projection this provider exists to avoid.
    [DllImport("UIAutomationCore.dll")]
    private static extern Windows.Win32.Foundation.LRESULT UiaReturnRawElementProvider(Windows.Win32.Foundation.HWND hwnd, Windows.Win32.Foundation.WPARAM wParam, Windows.Win32.Foundation.LPARAM lParam, [MarshalAs(UnmanagedType.Interface)] IRawElementProviderSimple el);

    [DllImport("UIAutomationCore.dll")]
    private static extern Windows.Win32.Foundation.HRESULT UiaHostProviderFromHwnd(Windows.Win32.Foundation.HWND hwnd, [MarshalAs(UnmanagedType.Interface)] out IRawElementProviderSimple provider);

    [DllImport("UIAutomationCore.dll")]
    private static extern Windows.Win32.Foundation.HRESULT UiaRaiseAutomationPropertyChangedEvent([MarshalAs(UnmanagedType.Interface)] IRawElementProviderSimple provider, int propertyId, [MarshalAs(UnmanagedType.Struct)] object oldValue, [MarshalAs(UnmanagedType.Struct)] object newValue);
}

// Mirrors the native ProviderOptions enum (UIAutomationCore.h). We report ServerSideProvider.
[Flags]
internal enum ProviderOptions
{
    ClientSideProvider = 0x1,
    ServerSideProvider = 0x2,
    NonClientAreaProvider = 0x4,
    OverrideProvider = 0x8,
    ProviderOwnsSetFocus = 0x10,
    UseComThreading = 0x20,
}

// Classic [ComImport] declaration of IRawElementProviderSimple (IID d6dd68d1-86fd-4332-8666-9abedea2d24c).
// Hand-declared so GetPropertyValue can return a managed object that the CLR marshals to VARIANT for us.
// The member ORDER must match the COM vtable: get_ProviderOptions, GetPatternProvider, GetPropertyValue,
// get_HostRawElementProvider.
[ComImport]
[Guid("d6dd68d1-86fd-4332-8666-9abedea2d24c")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
internal interface IRawElementProviderSimple
{
    ProviderOptions ProviderOptions { get; }

    [return: MarshalAs(UnmanagedType.IUnknown)]
    object? GetPatternProvider(int patternId);

    [return: MarshalAs(UnmanagedType.Struct)]
    object? GetPropertyValue(int propertyId);

    IRawElementProviderSimple? HostRawElementProvider { get; }
}
